# Generated by Django 3.2.25 on 2024-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrieveTableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False, verbose_name='Is the retrieve table running?')),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name='Date, tables retrieve started')),
                ('table_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current table name')),
                ('chunk', models.PositiveIntegerField(default=0, verbose_name='Current chunk number')),
                ('current_record', models.PositiveIntegerField(default=0, verbose_name='Current record counter')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Total records to be exported')),
                ('voter_device_id', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='voter device id')),
            ],
        ),
    ]
