# Generated by Django 5.0.3 on 2024-04-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieve_tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrievetablestate',
            name='voter_device_id',
        ),
        migrations.AddField(
            model_name='retrievetablestate',
            name='voter_api_device_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='voter_api_device_id'),
        ),
    ]
