# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleuser',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='we vote id for the Apple ID owner'),
        ),
    ]
