# Generated by Django 5.0.3 on 2024-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followissue',
            name='following_status',
            field=models.CharField(choices=[('FOLLOWING', 'Following'), ('STOP_FOLLOWING', 'Not Following'), ('FOLLOW_DISLIKE', 'Disliking'), ('STOP_DISLIKING', 'Not Disliking'), ('FOLLOW_IGNORE', 'Ignoring'), ('STOP_IGNORING', 'Not Ignoring')], db_index=True, default='FOLLOWING', max_length=15),
        ),
        migrations.AlterField(
            model_name='followorganization',
            name='following_status',
            field=models.CharField(choices=[('FOLLOWING', 'Following'), ('STOP_FOLLOWING', 'Not Following'), ('FOLLOW_DISLIKE', 'Disliking'), ('STOP_DISLIKING', 'Not Disliking'), ('FOLLOW_IGNORE', 'Ignoring'), ('STOP_IGNORING', 'Not Ignoring')], db_index=True, default='FOLLOWING', max_length=15),
        ),
    ]
