# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_alter_followissue_following_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcampaignx',
            name='campaignx_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='followcampaignx',
            name='campaignx_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followcampaignx',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followissue',
            name='issue_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='followissue',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='suggestedissuetofollow',
            name='issue_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='issue we vote id'),
        ),
        migrations.AlterField(
            model_name='suggestedissuetofollow',
            name='viewer_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='voter we vote id'),
        ),
        migrations.AlterField(
            model_name='suggestedorganizationtofollow',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='organization we vote id person 2'),
        ),
        migrations.AlterField(
            model_name='suggestedorganizationtofollow',
            name='viewer_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='voter we vote id person 1'),
        ),
    ]
