# Generated by Django 5.0.3 on 2024-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_alter_followcampaignx_campaignx_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followorganization',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followorganization',
            name='voter_linked_organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
