# Generated by Django 5.0.3 on 2024-07-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0004_alter_followorganization_organization_we_vote_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followorganization',
            old_name='voter_linked_organization_we_vote_id',
            new_name='organization_we_vote_id_that_is_following',
        ),
    ]
