#!/usr/bin/env python

import json
import os
import subprocess
import sys
import debugpy

def log(line: str):
    print(line, flush=True)

def load_environment_file(file: str) -> bool:
    if not os.path.exists(file):
        log(f"Unable to load env from file {file}, file does not exist.")
        return False
    log(f"Loading environment variables from file '{file}'")
    try:
        with open(file, 'r') as fh:
            variables = json.load(fh)
            for key, value in variables.items():
                if isinstance(value, bool):
                    value = str(value).lower()
                if key not in os.environ:
                    os.environ[key] = str(value)
    except json.JSONDecodeError:
        log(f"Error decoding JSON from {file}")
    except Exception as e:
        log(f"An error occurred while loading config variables: {e}")
    return True


load_environment_file(os.path.join("config", "environment_variables.json"))
load_environment_file(os.path.join("config", "environment_variables-template.json"))

log("Running 'manage.py makemigrations'")
os.system("python manage.py makemigrations")
log("Running 'manage.py migrate'")
os.system("python manage.py migrate")
log("Running 'manage.py createsuperuser'")
os.system("python manage.py createsuperuser --noinput")

# Start debugpy listener
try:
    log("Starting debugpy on 0.0.0.0:5678")
    debugpy.listen(("0.0.0.0", 5678))
    log("Debugger is ready and waiting for VS Code or PyCharm to attach...")
except Exception as e:
    log(f"Error starting debugpy: {e}")

sys.exit(subprocess.call(sys.argv[1:]))

