# Generated by Django 5.0.13 on 2025-11-27 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleUseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_validation', models.BinaryField(help_text='Field used to test if the passed validation key is valid.', verbose_name='Encoded Validation Data')),
                ('_expiration_datetime', models.DateTimeField(help_text='When this token expires.', verbose_name='token expiration datetime')),
                ('_json_data_encrypted', models.BinaryField(blank=True, default=None, help_text='Encrypted JSON blob for storing additional token data.', null=True, verbose_name='additional token data')),
                ('_created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when token was created.', verbose_name='token creation datetime')),
                ('_user', models.ForeignKey(help_text='The user this token belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='single_use_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Single Use Token',
                'verbose_name_plural': 'Single Use Tokens',
            },
        ),
    ]
