# Generated by Django 5.0.13 on 2025-11-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleusetoken',
            name='_user',
        ),
        migrations.AddField(
            model_name='singleusetoken',
            name='_user_id',
            field=models.BinaryField(default=None, help_text='The user this token is assigned to.', verbose_name='user we_vote_id'),
            preserve_default=False,
        ),
    ]
