# Generated by Django 5.0.13 on 2025-11-30 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_tokens', '0002_remove_singleusetoken__user_singleusetoken__user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleusetoken',
            name='_created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when token was created.', null=True, verbose_name='token creation datetime'),
        ),
        migrations.AlterField(
            model_name='singleusetoken',
            name='_expiration_datetime',
            field=models.DateTimeField(help_text='When this token expires.', null=True, verbose_name='token expiration datetime'),
        ),
        migrations.AlterField(
            model_name='singleusetoken',
            name='_user_id',
            field=models.BinaryField(help_text='The user this token is assigned to.', null=True, verbose_name='user we_vote_id'),
        ),
        migrations.AlterField(
            model_name='singleusetoken',
            name='_validation',
            field=models.BinaryField(help_text='Field used to test if the passed validation key is valid.', null=True, verbose_name='Encoded Validation Data'),
        ),
    ]
