# Generated by Django 5.0.13 on 2025-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_tokens', '0003_alter_singleusetoken__created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleusetoken',
            name='_scope',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'backup_one_table_to_s3')], default=0, help_text='The scope of the token.', verbose_name='scope'),
        ),
    ]
