# Generated by Django 5.0.13 on 2025-12-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_tokens', '0004_singleusetoken__scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleusetoken',
            name='_user_id',
        ),
    ]
