# Generated by Django 5.0.13 on 2025-12-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_tokens', '0005_remove_singleusetoken__user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleusetoken',
            name='_user_id',
            field=models.CharField(db_index=True, default=None, help_text='The user this token is assigned to.', max_length=255, null=True, verbose_name='user we_vote_id'),
        ),
    ]
