# Generated by Django 3.2.15 on 2022-09-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterGuidesGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_civic_election_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True)),
                ('number_of_voter_guides', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
