# Generated by Django 3.2.18 on 2023-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0002_voterguidesgenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguidepossibilityposition',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='voterguidepossibilityposition',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
