# Generated by Django 3.2.23 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0003_auto_20230608_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterguide',
            name='twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username'),
        ),
    ]
