# Generated by Django 3.2.25 on 2024-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0004_alter_voterguide_twitter_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguidepossibilityposition',
            name='ballot_item_state_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
