# Generated by Django 5.0.3 on 2024-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0005_voterguidepossibilityposition_ballot_item_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterguidepossibilityposition',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more info about this position'),
        ),
    ]
