# Generated by Django 5.0.3 on 2024-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0006_alter_voterguidepossibilityposition_more_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterguidepossibility',
            name='done_needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterguidepossibility',
            name='done_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterguidepossibility',
            name='verified_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voterguidepossibility',
            name='verified_by_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
