# Generated by Django 5.0.8 on 2024-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_guide', '0007_voterguidepossibility_done_needs_verification_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voterguide',
            index=models.Index(fields=['google_civic_election_id', 'voter_guide_owner_type', '-twitter_followers_count'], name='election_owner_followers'),
        ),
    ]
