# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsoutbounddescription',
            name='recipient_sms_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='sms we vote id for recipient'),
        ),
        migrations.AlterField(
            model_name='smsoutbounddescription',
            name='recipient_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the recipient if we have it'),
        ),
        migrations.AlterField(
            model_name='smsoutbounddescription',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
        migrations.AlterField(
            model_name='smsphonenumber',
            name='voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sms owner'),
        ),
        migrations.AlterField(
            model_name='smsphonenumber',
            name='we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote id of this sms address'),
        ),
        migrations.AlterField(
            model_name='smsscheduled',
            name='recipient_sms_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sms'),
        ),
        migrations.AlterField(
            model_name='smsscheduled',
            name='recipient_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the recipient'),
        ),
        migrations.AlterField(
            model_name='smsscheduled',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
    ]
