# Generated by Django 3.2.16 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollinglocation',
            name='google_civic_error_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pollinglocationlogentry',
            name='is_from_google_civic',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
    ]
