# Generated by Django 5.0.3 on 2024-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0002_auto_20230126_1420'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollinglocationlogentry',
            index=models.Index(fields=['kind_of_log_entry', 'log_entry_deleted'], name='kind_of_log_entry_and_deleted'),
        ),
    ]
