# Generated by Django 5.0.3 on 2024-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0003_pollinglocationlogentry_kind_of_log_entry_and_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollinglocationlogentry',
            index=models.Index(fields=['polling_location_we_vote_id', 'kind_of_log_entry', 'log_entry_deleted'], name='log_entry_one_location_index'),
        ),
    ]
