# Generated by Django 5.0.3 on 2024-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0004_pollinglocationlogentry_log_entry_one_location_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollinglocationlogentry',
            index=models.Index(fields=['polling_location_we_vote_id', 'kind_of_log_entry'], name='we_vote_id_and_kind_index'),
        ),
        migrations.AddIndex(
            model_name='pollinglocationlogentry',
            index=models.Index(fields=['kind_of_log_entry', 'polling_location_we_vote_id'], name='kind_and_we_vote_id_index'),
        ),
    ]
