# Generated by Django 5.0.3 on 2024-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0005_pollinglocationlogentry_we_vote_id_and_kind_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollinglocation',
            index=models.Index(fields=['state', 'polling_location_deleted'], name='state_and_not_deleted'),
        ),
    ]
