# Generated by Django 5.0.3 on 2024-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0006_pollinglocation_state_and_not_deleted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollinglocationlogentry',
            index=models.Index(fields=['log_entry_deleted', 'kind_of_log_entry'], name='deleted_and_kind_of_log_entry'),
        ),
    ]
