# Generated by Django 5.0.8 on 2024-09-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_location', '0007_pollinglocationlogentry_deleted_and_kind_of_log_entry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pollinglocationlogentry',
            name='kind_and_we_vote_id_index',
        ),
        migrations.RemoveIndex(
            model_name='pollinglocationlogentry',
            name='deleted_and_kind_of_log_entry',
        ),
    ]
