# Generated by Django 3.2.13 on 2022-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='vote_usa_same_day_election_suffix_list',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
