# Generated by Django 3.2.14 on 2022-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_election_vote_usa_same_day_election_suffix_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='google_civic_election_id',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='google civic election id'),
        ),
        migrations.AlterField(
            model_name='election',
            name='ignore_this_election',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='include_in_list_for_voters',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
