# Generated by Django 3.2.19 on 2023-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20220727_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='ctcl_uuid2',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='ctcl_uuid3',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
