name: wevote

services:
  db:
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-wevoteserverdb}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16-alpine
    networks:
      - wevote
    ports:
      - "127.0.0.1:5432:5432" # to allow postgres clients on the host machine to connect to the database at localhost:5432
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  localstack:
    image: localstack/localstack:4.14.0
    networks:
      - wevote
    volumes:
      - localstack:/var/lib/localstack
    environment:
      PERSISTENCE: 1
  
  api:
    build:
      dockerfile: docker/Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - DATABASE_NAME=${DATABASE_NAME:-wevoteserverdb}
      - DATABASE_NAME_READONLY=${DATABASE_NAME:-wevoteserverdb}
      - DATABASE_HOST=db
      - DATABASE_HOST_READONLY=db
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_USER_READONLY=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-admin}
      - DATABASE_PASSWORD_READONLY=${DATABASE_PASSWORD:-admin}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_PORT_READONLY=${DATABASE_PORT:-5432}
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
    volumes:
      - .:/wevote/code
    networks:
      - wevote
    ports:
      - "127.0.0.1:8000:8000" # this allows access to the WeVote API at localhost:8000

networks:
  wevote:
    name: wevote
    external: true


volumes:
  localstack:
  postgres_data:
