target-version = "py313"

[format]
exclude = ["**/*"]

[lint]
select = [
    "DJ",       # flake8-django
    "E4",       # codestyle: imports
    "E7",       # codestyle: statement check
    "E9",       # io error
    "F",        # Pyflakes rules
    "PLR6301"   # unused self parameters
]
ignore = [
    "F841"      # unused variables
]
preview = true
explicit-preview-rules = true
