# Generated by Django 3.2.16 on 2022-12-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignxpolitician',
            name='candidate_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
