# Generated by Django 3.2.18 on 2023-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaignxpolitician_candidate_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='campaign_description_linked_to_twitter',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='campaignx',
            name='linked_politician_we_vote_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
