# Generated by Django 3.2.18 on 2023-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20230410_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='date_last_updated_from_politician',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='campaignx',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignx',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignx',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
    ]
