# Generated by Django 3.2.18 on 2023-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20230516_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignxsupporter',
            name='linked_position_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignxsupporter',
            name='is_subscribed_by_email',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
