# Generated by Django 3.2.18 on 2023-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20230521_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignxsupporter',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
