# Generated by Django 3.2.23 on 2023-11-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_alter_campaignxsupporter_voter_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='ocd_id_state_mismatch_found',
            field=models.BooleanField(default=False),
        ),
    ]
