# Generated by Django 3.2.23 on 2023-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaignx_ocd_id_state_mismatch_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='ocd_id_state_mismatch_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
