# Generated by Django 3.2.23 on 2023-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_campaignx_ocd_id_state_mismatch_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='ocd_id_state_mismatch_checked_politician',
            field=models.BooleanField(default=False),
        ),
    ]
