# Generated by Django 3.2.23 on 2023-11-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_campaignx_ocd_id_state_mismatch_checked_politician'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignXEntriesAreNotDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx1_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='first campaignx we are tracking')),
                ('campaignx2_we_vote_id', models.CharField(max_length=255, null=True, verbose_name='second campaignx we are tracking')),
            ],
        ),
    ]
