# Generated by Django 3.2.23 on 2023-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignxentriesarenotduplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='ocd_id_state_mismatch_checked_campaign_title',
            field=models.BooleanField(default=False),
        ),
    ]
