# Generated by Django 3.2.23 on 2023-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_campaignx_ocd_id_state_mismatch_checked_campaign_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignx',
            name='linked_politician_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
