# Generated by Django 3.2.23 on 2023-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_alter_campaignx_linked_politician_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='profile_image_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
