# Generated by Django 5.0.3 on 2024-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_campaignx_profile_image_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='linked_politician_we_vote_id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
