# Generated by Django 5.0.3 on 2024-05-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_campaignx_linked_politician_we_vote_id_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignXEntriesArePossibleDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignx1_we_vote_id', models.CharField(max_length=255, null=True)),
                ('campaignx2_we_vote_id', models.CharField(max_length=255, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaignx',
            name='state_code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
