# Generated by Django 5.0.3 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0015_campaignxentriesarepossibleduplicates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='opposers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
