# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0016_campaignx_opposers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignxentriesarenotduplicates',
            name='campaignx1_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='first campaignx we are tracking'),
        ),
        migrations.AlterField(
            model_name='campaignxentriesarenotduplicates',
            name='campaignx2_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='second campaignx we are tracking'),
        ),
        migrations.AlterField(
            model_name='campaignxentriesarepossibleduplicates',
            name='campaignx1_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignxentriesarepossibleduplicates',
            name='campaignx2_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignxlistedbyorganization',
            name='campaignx_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaignxlistedbyorganization',
            name='site_owner_organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
