# Generated by Django 5.0.3 on 2024-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0017_alter_campaignxentriesarenotduplicates_campaignx1_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='supporters_count_to_update_with_bulk_script',
            field=models.BooleanField(default=True),
        ),
    ]
