# Generated by Django 5.0.3 on 2024-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0018_campaignx_supporters_count_to_update_with_bulk_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
