# Generated by Django 5.0.3 on 2024-07-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0019_campaignx_organization_we_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignx',
            name='seo_friendly_path',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
