# Generated by Django 5.0.3 on 2024-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0020_alter_campaignx_seo_friendly_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignx',
            name='linked_politician_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
