# Generated by Django 5.0.13 on 2025-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0021_alter_campaignx_linked_politician_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignx',
            name='passkey_for_creating_campaign_owner',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
    ]
