# Generated by Django 3.2.15 on 2022-10-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chosen_domain_string2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='chosen_domain_string3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
