# Generated by Django 3.2.17 on 2023-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221007_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded'), ('VOTE_USA', 'Vote-USA')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_handle2_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_handle_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_facebook_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_facebook_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_facebook_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_twitter_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_twitter_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_twitter_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_uploaded_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_uploaded_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_uploaded_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_vote_usa_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_vote_usa_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='we_vote_hosted_profile_vote_usa_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='wikipedia_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
    ]
