# Generated by Django 3.2.18 on 2023-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20230210_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_name', models.CharField(default=None, max_length=255, null=True)),
                ('changed_by_voter_we_vote_id', models.CharField(default=None, max_length=255, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('log_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
                ('organization_we_vote_id', models.CharField(default=None, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
