# Generated by Django 3.2.20 on 2023-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='client domain name for we vote site'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string2',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string3',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
