# Generated by Django 3.2.23 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20230804_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_instagram_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='organization instagram username'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='organization twitter username'),
        ),
    ]
