# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_facebook_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_contact_form_url',
            field=models.TextField(null=True, verbose_name='url of the contact us form'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_website',
            field=models.TextField(null=True, verbose_name='url of the endorsing organization'),
        ),
    ]
