# Generated by Django 5.0.3 on 2024-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_organization_contact_form_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_facebook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
