# Generated by Django 5.0.3 on 2024-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_organization_organization_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_instagram_handle',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='organization instagram username'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_twitter_handle',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='organization twitter username'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state_served_code',
            field=models.CharField(db_index=True, max_length=2, null=True, verbose_name='state this organization serves'),
        ),
    ]
