# Generated by Django 5.0.3 on 2024-07-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_organization_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='twitter_followers_count',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='number of twitter followers'),
        ),
    ]
