# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_organization_twitter_followers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationchangelog',
            name='changed_by_voter_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationchangelog',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationlinktohashtag',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='organizationlinktowordorphrase',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiplinktovoter',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='we vote id for organization'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiplinktovoter',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='we vote id for the voter owner'),
        ),
        migrations.AlterField(
            model_name='organizationreserveddomain',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationteammember',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationteammember',
            name='team_member_organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
