# Generated by Django 5.0.3 on 2024-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organizationchangelog_changed_by_voter_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['politician_we_vote_id', 'state_served_code', 'organization_name', '-twitter_followers_count'], name='organization_politicians_match'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['chosen_domain_string', 'chosen_domain_string2', 'chosen_domain_string3', 'chosen_subdomain_string'], name='site_configuration'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['we_vote_id', '-twitter_followers_count'], name='orgs_by_twitter_followers'),
        ),
    ]
