# Generated by Django 5.0.3 on 2024-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_organization_organization_politicians_match_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organization_politicians_sort',
            old_name='organization_politicians_match',
        ),
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='client domain name for we vote site'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='chosen_domain_string3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['politician_we_vote_id', 'organization_name'], name='orgs_by_politician'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['politician_we_vote_id', 'state_served_code', 'organization_name'], name='organization_politicians_match'),
        ),
    ]
