# Generated by Django 5.0.8 on 2024-08-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_rename_organization_politicians_match_organization_politicians_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationteammember',
            name='can_edit_challenge_owned_by_organization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationteammember',
            name='can_moderate_challenge_owned_by_organization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationteammember',
            name='can_send_updates_for_challenge_owned_by_organization',
            field=models.BooleanField(default=True),
        ),
    ]
