# Generated by Django 5.0.11 on 2025-02-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_organizationteammember_can_edit_challenge_owned_by_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationsAreNotDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization1_we_vote_id', models.CharField(db_index=True, max_length=255, null=True, verbose_name='first organization we are tracking')),
                ('organization2_we_vote_id', models.CharField(db_index=True, max_length=255, null=True, verbose_name='second organization we are tracking')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationsArePossibleDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization1_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('organization2_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
