# Generated by Django 5.0.13 on 2025-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_organizationsarenotduplicates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bluesky_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tiktok_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
