# Generated by Django 5.0.13 on 2025-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_organization_bluesky_handle_organization_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='augmentation_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_defunct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='qa_done',
            field=models.BooleanField(default=False),
        ),
    ]
