# Generated by Django 5.0.13 on 2025-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organization_augmentation_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='help_needed',
            field=models.BooleanField(default=False),
        ),
    ]
