# Generated by Django 3.2.17 on 2023-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='forced_sort_order',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
