# Generated by Django 5.0.3 on 2024-07-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_forced_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlinktoissue',
            name='link_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name=''),
        ),
    ]
