# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_organizationlinktoissue_link_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id of this issue'),
        ),
    ]
