# Generated by Django 5.0.7 on 2024-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_issue_we_vote_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['hide_issue', 'we_vote_id'], name='hide_issue_we_vote_id'),
        ),
        migrations.AddIndex(
            model_name='organizationlinktoissue',
            index=models.Index(fields=['organization_we_vote_id', 'link_active'], name='organization_and_link_active'),
        ),
        migrations.AddIndex(
            model_name='organizationlinktoissue',
            index=models.Index(fields=['issue_we_vote_id', 'organization_we_vote_id', 'link_active'], name='issue_org_link_active'),
        ),
    ]
