# Generated by Django 5.0.8 on 2024-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_hide_issue_we_vote_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationlinktoissue',
            name='issue_org_link_active',
        ),
        migrations.AddIndex(
            model_name='organizationlinktoissue',
            index=models.Index(fields=['organization_we_vote_id', 'issue_we_vote_id', 'link_active'], name='org_issue_link_active'),
        ),
    ]
