# Generated by Django 3.2.16 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeToOfficeHeldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('office_held_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('politician_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('years_in_office_flags', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='representative',
            name='ballotpedia_page_title',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='ballotpedia_photo_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='ballotpedia_representative_id',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='ballotpedia_representative_name',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='facebook_profile_image_url_https',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='google_civic_election_id',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='google_plus_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='linkedin_photo_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='maplight_id',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='order_on_ballot',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='other_source_photo_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='other_source_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='photo_url_from_maplight',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='photo_url_from_vote_smart',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='vote_smart_id',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='wikipedia_page_id',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='wikipedia_page_title',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='wikipedia_photo_url',
        ),
        migrations.AddField(
            model_name='representative',
            name='date_last_updated_from_politician',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='google_civic_profile_image_url_https',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='google_civic_representative_name2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='google_civic_representative_name3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='instagram_followers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='representative',
            name='instagram_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='photo_url_from_google_civic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_contact_form_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_email2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_email3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_phone2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_phone3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_twitter_handle2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_twitter_handle3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_url2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='representative_url3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='twitter_handle2_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='twitter_handle_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='vote_usa_politician_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='wikipedia_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year_in_office_2023',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year_in_office_2024',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year_in_office_2025',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year_in_office_2026',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='ballotpedia_representative_url',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='url of representative on ballotpedia'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='facebook_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='google_civic_representative_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='representative_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='state_code',
            field=models.CharField(max_length=2, null=True, verbose_name='state this representative serves'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter_followers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter_profile_background_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='tile-able background from twitter'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter_profile_banner_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='profile banner image from twitter'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='url of logo from twitter'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter_url',
            field=models.TextField(blank=True, null=True, verbose_name='twitter url of representative'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
