# Generated by Django 3.2.16 on 2023-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0002_auto_20230126_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='politician_deduplication_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='politician_match_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
