# Generated by Django 3.2.17 on 2023-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0003_auto_20230201_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativesMissingFromPollingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date representatives last requested')),
                ('error_message', models.TextField(default=None, null=True)),
                ('is_from_google_civic', models.BooleanField(default=False)),
                ('issue_resolved', models.BooleanField(default=False)),
                ('polling_location_we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='we vote permanent id of the map point')),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
            ],
        ),
    ]
