# Generated by Django 3.2.17 on 2023-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0005_auto_20230208_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='is_battleground_race_2022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='is_battleground_race_2023',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='is_battleground_race_2024',
            field=models.BooleanField(default=False),
        ),
    ]
