# Generated by Django 3.2.18 on 2023-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0008_representative_seo_friendly_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='seo_friendly_path_date_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
