# Generated by Django 3.2.18 on 2023-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0009_representative_seo_friendly_path_date_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='office_held_district_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
