# Generated by Django 3.2.18 on 2023-04-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0010_representative_office_held_district_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepresentativeToOfficeHeldLink',
        ),
    ]
