# Generated by Django 3.2.18 on 2023-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0012_auto_20230504_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='supporters_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
