# Generated by Django 3.2.23 on 2023-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0014_auto_20230629_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='seo_friendly_path',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
