# Generated by Django 3.2.23 on 2023-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0015_alter_representative_seo_friendly_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='profile_image_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
