# Generated by Django 3.2.23 on 2024-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0016_representative_profile_image_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('BALLOTPEDIA', 'Ballotpedia'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded'), ('VOTE_USA', 'Vote-USA'), ('WIKIPEDIA', 'Wikipedia')], default='UNKNOWN', max_length=11),
        ),
    ]
