# Generated by Django 5.0.13 on 2025-10-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representative', '0017_alter_representative_profile_image_type_currently_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='is_claimed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
