# Generated by Django 3.2.13 on 2022-04-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_auto_20220429_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votercontactemail',
            name='city',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='voter_we_vote_id',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='we_vote_hosted_profile_image_url_medium',
        ),
        migrations.RemoveField(
            model_name='votercontactemail',
            name='zip_code',
        ),
    ]
