# Generated by Django 3.2.13 on 2022-04-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_auto_20220429_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='votercontactemail',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='display_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='first_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='last_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='middle_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='zip_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
