# Generated by Django 3.2.13 on 2022-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20220429_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='state_code_for_display',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='state_code_for_display_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='state_code_for_display_updated',
            field=models.BooleanField(default=False),
        ),
    ]
