# Generated by Django 3.2.13 on 2022-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20220522_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='friend_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
