# Generated by Django 3.2.14 on 2022-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_voter_friend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='votercontactemail',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
