# Generated by Django 3.2.15 on 2022-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_votercontactemail_is_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='votercontactemail',
            name='api_type',
            field=models.CharField(default='google', max_length=16, verbose_name='apple google android etc'),
        ),
        migrations.AddField(
            model_name='votercontactemail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='contact phone number'),
        ),
    ]
