# Generated by Django 3.2.19 on 2023-07-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_votermergelog_votermergestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='county_fips_code',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='county_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='county_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
