# Generated by Django 3.2.19 on 2023-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_auto_20230707_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterIssuesLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('likely_democrat_from_issues', models.BooleanField(default=None, null=True)),
                ('likely_republican_from_issues', models.BooleanField(default=None, null=True)),
                ('likely_party_from_issues_analyzed', models.BooleanField(default=False)),
                ('affordable_housing', models.BooleanField(default=None, null=True)),
                ('animals', models.BooleanField(default=None, null=True)),
                ('bicycling', models.BooleanField(default=None, null=True)),
                ('borders', models.BooleanField(default=None, null=True)),
                ('climate_change', models.BooleanField(default=None, null=True)),
                ('color', models.BooleanField(default=None, null=True)),
                ('conservative', models.BooleanField(default=None, null=True)),
                ('democratic_clubs', models.BooleanField(default=None, null=True)),
                ('democratic_politicians', models.BooleanField(default=None, null=True)),
                ('green_clubs', models.BooleanField(default=None, null=True)),
                ('green_politicians', models.BooleanField(default=None, null=True)),
                ('gun_reform', models.BooleanField(default=None, null=True)),
                ('homeless', models.BooleanField(default=None, null=True)),
                ('immigration', models.BooleanField(default=None, null=True)),
                ('independent_politicians', models.BooleanField(default=None, null=True)),
                ('justice_reform', models.BooleanField(default=None, null=True)),
                ('lgbtq', models.BooleanField(default=None, null=True)),
                ('libertarian_clubs', models.BooleanField(default=None, null=True)),
                ('libertarian_politicians', models.BooleanField(default=None, null=True)),
                ('low_income', models.BooleanField(default=None, null=True)),
                ('maga', models.BooleanField(default=None, null=True)),
                ('marijuana', models.BooleanField(default=None, null=True)),
                ('money_in_politics', models.BooleanField(default=None, null=True)),
                ('pro_choice', models.BooleanField(default=None, null=True)),
                ('pro_life', models.BooleanField(default=None, null=True)),
                ('pro_public_schools', models.BooleanField(default=None, null=True)),
                ('pro_school_choice', models.BooleanField(default=None, null=True)),
                ('progressive', models.BooleanField(default=None, null=True)),
                ('public_healthcare', models.BooleanField(default=None, null=True)),
                ('republican_clubs', models.BooleanField(default=None, null=True)),
                ('republican_politicians', models.BooleanField(default=None, null=True)),
                ('second_amendment', models.BooleanField(default=None, null=True)),
                ('social_security', models.BooleanField(default=None, null=True)),
                ('student_debt', models.BooleanField(default=None, null=True)),
                ('voting_rights', models.BooleanField(default=None, null=True)),
                ('womens_equality', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='county_id',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_issues_lookup_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='county_fips_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
