# Generated by Django 3.2.19 on 2023-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_auto_20230709_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterissueslookup',
            name='likely_green_from_issues',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voterissueslookup',
            name='likely_left_from_issues',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voterissueslookup',
            name='likely_libertarian_from_issues',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='voterissueslookup',
            name='likely_right_from_issues',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
