# Generated by Django 3.2.20 on 2023-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0012_auto_20230709_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteraddress',
            name='county_fips_code',
            field=models.CharField(max_length=5, null=True, verbose_name='FIPS code for this county'),
        ),
        migrations.AddField(
            model_name='voteraddress',
            name='county_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voteraddress',
            name='invalid_address',
            field=models.BooleanField(null=True, verbose_name='Garbage, misspelled, or unparsable address'),
        ),
    ]
