# Generated by Django 3.2.20 on 2023-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0013_auto_20230729_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_signed_in_cached',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
