# Generated by Django 3.2.23 on 2024-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_voter_is_signed_in_cached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded')], default='UNKNOWN', max_length=11),
        ),
    ]
