# Generated by Django 3.2.24 on 2024-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_alter_voter_profile_image_type_currently_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_voter_manager',
            field=models.BooleanField(default=False),
        ),
    ]
