# Generated by Django 3.2.24 on 2024-03-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0016_voter_is_voter_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='twitter_access_secret',
            new_name='twitter_voters_access_secret',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='twitter_access_token',
            new_name='twitter_voters_access_token_secret',
        ),
    ]
