# Generated by Django 3.2.25 on 2024-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0017_auto_20240303_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='votermergestatus',
            name='move_candidate_change_log_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votermergestatus',
            name='move_candidate_change_log_milliseconds',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='votermergestatus',
            name='move_voter_change_log_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votermergestatus',
            name='move_voter_change_log_milliseconds',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
