# Generated by Django 3.2.25 on 2024-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0018_auto_20240309_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='linked_organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='we vote id for linked organization'),
        ),
    ]
