# Generated by Django 5.0.3 on 2024-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0019_alter_voter_linked_organization_we_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='twitter_voters_access_secret',
        ),
        migrations.AddField(
            model_name='voter',
            name='twitter_voters_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='twitter access token'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='twitter_voters_access_token_secret',
            field=models.TextField(blank=True, null=True, verbose_name='twitter access token secret'),
        ),
    ]
