# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0020_remove_voter_twitter_voters_access_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='primary_email_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='we vote id for primary email for this voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='primary_sms_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='we vote id for primary phone number'),
        ),
    ]
