# Generated by Django 5.0.3 on 2024-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0021_alter_voter_primary_email_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['linked_organization_we_vote_id'], name='voter_fetch_voter_by_org_index'),
        ),
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['primary_email_we_vote_id', 'primary_sms_we_vote_id', 'twitter_id', 'facebook_id'], name='voter_signin_count_index'),
        ),
    ]
