# Generated by Django 5.0.3 on 2024-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0022_voter_voter_fetch_voter_by_org_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voter',
            index=models.Index(fields=['linked_organization_we_vote_id', 'we_vote_id'], name='fetch_voter_by_org2_index'),
        ),
    ]
