# Generated by Django 5.0.3 on 2024-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0023_voter_fetch_voter_by_org2_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='linked_organization_we_vote_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='we vote id for linked organization'),
        ),
    ]
