# Generated by Django 5.0.8 on 2024-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0024_alter_voter_linked_organization_we_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteraddress',
            name='voter_id',
            field=models.BigIntegerField(verbose_name='voter unique identifier'),
        ),
        migrations.AddIndex(
            model_name='voteraddress',
            index=models.Index(fields=['voter_id'], name='voter_id_address'),
        ),
        migrations.AddIndex(
            model_name='voteraddress',
            index=models.Index(fields=['voter_id', 'address_type'], name='voter_id_type'),
        ),
    ]
