# Generated by Django 5.0.8 on 2024-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0025_alter_voteraddress_voter_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voteraddress',
            index=models.Index(fields=['voter_id', '-date_last_changed'], name='voter_id_address_date'),
        ),
    ]
