# Generated by Django 5.0.8 on 2024-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0026_voteraddress_voter_id_address_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='votermergestatus',
            name='move_challenges_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votermergestatus',
            name='move_challenges_milliseconds',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
