# Generated by Django 5.0.13 on 2026-01-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0027_votermergestatus_move_challenges_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='app_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='app review (or negative bypass) date'),
        ),
        migrations.AddField(
            model_name='voter',
            name='app_review_platform',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='platform of reviewed app'),
        ),
        migrations.AddField(
            model_name='voter',
            name='app_review_state',
            field=models.CharField(choices=[('NONE', 'None'), ('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], default='NONE', max_length=11),
        ),
        migrations.AddField(
            model_name='voter',
            name='app_review_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='version of reviewed app'),
        ),
    ]
