# Generated by Django 3.2.24 on 2024-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterauthresponse',
            old_name='twitter_access_secret',
            new_name='twitter_voters_access_secret',
        ),
        migrations.RenameField(
            model_name='twitterauthresponse',
            old_name='twitter_access_token',
            new_name='twitter_voters_access_token_secret',
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_description',
            field=models.TextField(blank=True, null=True, verbose_name='twitter description'),
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_location',
            field=models.TextField(blank=True, null=True, verbose_name='twitter location'),
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_verified',
            field=models.BooleanField(default=False, verbose_name='twitter verified'),
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_verified_type',
            field=models.TextField(default='', verbose_name='twitter verified type'),
        ),
    ]
