# Generated by Django 5.0.3 on 2024-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_twitter', '0002_auto_20240303_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterauthresponse',
            name='twitter_voters_access_secret',
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_voters_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='twitter access token'),
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_voters_oauth_token',
            field=models.TextField(blank=True, null=True, verbose_name='twitter voter client oauth_token'),
        ),
        migrations.AddField(
            model_name='twitterauthresponse',
            name='twitter_voters_oauth_verifier',
            field=models.TextField(blank=True, null=True, verbose_name='twitter voter client oauth_verifier'),
        ),
        migrations.AlterField(
            model_name='twitterauthresponse',
            name='twitter_voters_access_token_secret',
            field=models.TextField(blank=True, null=True, verbose_name='twitter access token secret'),
        ),
    ]
