# Generated by Django 3.2.17 on 2023-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='date_last_updated_from_twitter',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_handle_updates_failing',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_profile_background_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='tile-able background from twitter'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_profile_banner_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='profile banner image from twitter'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='url of logo from twitter'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted large image url'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted medium image url'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted tiny image url'),
        ),
    ]
