# Generated by Django 3.2.23 on 2024-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20230208_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterApiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('kind_of_action', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='kind of call to Twitter')),
                ('google_civic_election_id', models.PositiveIntegerField(db_index=True, null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApiCounterDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_action', models.DateField(verbose_name='date of action')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to Twitter')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApiCounterMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('month_of_action', models.SmallIntegerField(verbose_name='number of the month')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to Twitter')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApiCounterWeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_action', models.SmallIntegerField(verbose_name='year of action')),
                ('week_of_action', models.SmallIntegerField(verbose_name='number of the week')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to Twitter')),
                ('google_civic_election_id', models.PositiveIntegerField(null=True, verbose_name='google civic election id')),
            ],
        ),
    ]
