# Generated by Django 3.2.25 on 2024-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twitterapicounter_twitterapicounterdailysummary_twitterapicountermonthlysummary_twitterapicounterwee'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterapicounter',
            name='candidate_name',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter screen name / handle'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='disambiguator',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='disambiguate within the function'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='function',
            field=models.CharField(max_length=255, null=True, verbose_name='function'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='search_term',
            field=models.CharField(max_length=255, null=True, verbose_name='search term to API'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='text',
            field=models.CharField(max_length=255, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='username',
            field=models.CharField(max_length=64, null=True, verbose_name='twitter screen name / handle'),
        ),
        migrations.AddField(
            model_name='twitterapicounter',
            name='voter_we_vote_id',
            field=models.CharField(max_length=255, null=True, verbose_name='voter we vote id'),
        ),
    ]
