# Generated by Django 3.2.25 on 2024-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20240308_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='date_last_updated_from_twitter',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='twitter big integer id'),
        ),
    ]
