# Generated by Django 3.2.25 on 2024-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20240311_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterapicounter',
            name='success',
            field=models.BooleanField(db_index=True, default=True, verbose_name='api call succeeded'),
        ),
    ]
