# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_twitterapicounter_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='organization_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='twitterapicounter',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='voter we vote id'),
        ),
        migrations.AlterField(
            model_name='twitterlinkpossibility',
            name='candidate_campaign_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='candidate we vote id'),
        ),
        migrations.AlterField(
            model_name='twitterlinktoorganization',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='we vote id for the org owner'),
        ),
        migrations.AlterField(
            model_name='twitterlinktovoter',
            name='twitter_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='twitter big integer id'),
        ),
        migrations.AlterField(
            model_name='twitterlinktovoter',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='we vote id for the voter owner'),
        ),
    ]
