# Generated by Django 3.2.16 on 2022-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidedailymetrics',
            name='shared_items_clicked_today',
            field=models.PositiveIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='sitewidedailymetrics',
            name='shared_link_clicked_count_today',
            field=models.PositiveIntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='sitewidedailymetrics',
            name='shared_link_clicked_unique_viewers_today',
            field=models.PositiveIntegerField(null=True, verbose_name=''),
        ),
    ]
