# Generated by Django 5.0.3 on 2024-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20221123_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsaction',
            name='ballot_item_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='analyticsaction',
            name='state_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='state_code'),
        ),
    ]
