# Generated by Django 5.0.7 on 2024-08-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticsaction_ballot_item_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsaction',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
