# Generated by Django 5.0.8 on 2024-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticsaction_politician_we_vote_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['google_civic_election_id', 'action_constant'], name='election_action_constant'),
        ),
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['voter_we_vote_id', 'action_constant'], name='voter_action_constant'),
        ),
    ]
