# Generated by Django 5.0.8 on 2024-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analyticsaction_election_action_constant_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['voter_we_vote_id', 'date_as_integer'], name='voter_date'),
        ),
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['voter_we_vote_id'], name='voter_index'),
        ),
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['date_as_integer'], name='date_as_integer_index'),
        ),
        migrations.AddIndex(
            model_name='analyticsaction',
            index=models.Index(fields=['date_as_integer', 'is_signed_in'], name='date_as_integer_signed_in'),
        ),
    ]
