# Generated by Django 3.2.17 on 2023-02-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeIpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of the captcha test')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='user ip address')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='ISO Country code from GEOIP')),
                ('voter_we_vote_id', models.CharField(max_length=255, verbose_name='Captcha session we vote user id')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='voters email address, this is checked before they enter it on the donation form, so only what is in the voter record')),
                ('captcha_score', models.FloatField(null=True, verbose_name='reCaptcha score returned from Google')),
                ('captcha_success', models.BooleanField(default=True, verbose_name='reCaptcha success returned from Google')),
                ('blocked_by_captcha', models.BooleanField(default=True, verbose_name='Did Google reCaptcha cause a block')),
                ('blocked_by_country', models.BooleanField(default=True, verbose_name='Did our country check cause a block')),
                ('blocked_by_frequency_hours', models.BooleanField(default=True, verbose_name='Did users frequency of donating cause a block (initially five in an hour) ')),
                ('blocked_by_frequency_days', models.BooleanField(default=True, verbose_name='Did users frequency of donating cause a block (initially twenty in a week')),
            ],
        ),
    ]
