# Generated by Django 3.2.15 on 2022-09-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0002_auto_20220727_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocess',
            name='kind_of_process',
            field=models.CharField(choices=[('ACTIVITY_NOTICE_PROCESS', 'Create, update, or schedule to send Activity Notices'), ('API_REFRESH_REQUEST', 'Make sure we have cached a recent return from a specific API'), ('AUGMENT_ANALYTICS_ACTION_WITH_ELECTION_ID', 'Add election id to AnalyticsAction'), ('AUGMENT_ANALYTICS_ACTION_WITH_FIRST_VISIT', 'Mark first AnalyticsAction per day'), ('CALCULATE_SITEWIDE_VOTER_METRICS', 'Sitewide voter metrics for all time'), ('CALCULATE_SITEWIDE_DAILY_METRICS', 'Sitewide daily metrics'), ('CALCULATE_SITEWIDE_ELECTION_METRICS', 'Sitewide election metrics'), ('CALCULATE_ORGANIZATION_DAILY_METRICS', 'Organization specific daily metrics'), ('CALCULATE_ORGANIZATION_ELECTION_METRICS', 'Organization specific election metrics'), ('GENERATE_VOTER_GUIDES', 'Generate voter guides'), ('RETRIEVE_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', 'Retrieve Ballot Items from Map Points'), ('REFRESH_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', 'Refresh Ballot Items from BallotReturned Map Points'), ('REFRESH_BALLOT_ITEMS_FROM_VOTERS', 'Refresh Ballot Items from Voter Custom Addresses'), ('SEARCH_TWITTER_FOR_CANDIDATE_TWITTER_HANDLE', 'Search for Candidate Twitter Handles')], db_index=True, default='RETRIEVE_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', max_length=50),
        ),
    ]
