# Generated by Django 3.2.16 on 2023-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0004_auto_20230104_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactioncandidate',
            name='candidate_twitter_handle2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactioncandidate',
            name='candidate_twitter_handle3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchrowactioncandidate',
            name='candidate_twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchrowactionpolitician',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('N', 'Nonbinary'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender'),
        ),
    ]
