# Generated by Django 3.2.16 on 2023-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0005_auto_20230106_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRowActionOfficeHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_set_id', models.PositiveIntegerField(null=True, verbose_name='unique id of batch set')),
                ('batch_header_id', models.PositiveIntegerField(db_index=True, verbose_name='unique id of header row')),
                ('batch_row_id', models.PositiveIntegerField(db_index=True, verbose_name='unique id of batch row')),
                ('kind_of_action', models.CharField(choices=[('IMPORT_TO_BE_DETERMINED', 'To Be Determined'), ('DO_NOT_PROCESS', 'Do not process'), ('IMPORT_CREATE', 'Create'), ('IMPORT_ADD_TO_EXISTING', 'Add to Existing')], db_index=True, default='IMPORT_TO_BE_DETERMINED', max_length=40)),
                ('office_held_we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='we vote permanent id for this office held')),
                ('office_held_name', models.CharField(max_length=255, verbose_name='name of the office held')),
                ('office_held_name_es', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the office held in Spanish')),
                ('google_civic_office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='office name exactly as received from google civic')),
                ('google_civic_election_id', models.CharField(db_index=True, max_length=255, verbose_name='google civic election id')),
                ('google_civic_election_id_new', models.PositiveIntegerField(default=0, verbose_name='google civic election id')),
                ('ocd_division_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ocd division id')),
                ('maplight_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='maplight unique identifier')),
                ('ballotpedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ballotpedia unique identifier')),
                ('wikipedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='wikipedia unique identifier')),
                ('number_elected', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic number of candidates who will be elected')),
                ('state_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='state this office serves')),
                ('primary_party', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='district name')),
                ('district_scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district scope')),
                ('district_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district id')),
                ('contest_level0', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 0')),
                ('contest_level1', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 1')),
                ('contest_level2', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 2')),
                ('electorate_specifications', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('special', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('ctcl_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='ctcl uuid')),
                ('office_held_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='office description')),
                ('office_held_description_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='office description spanish')),
                ('office_held_is_partisan', models.BooleanField(default=False, verbose_name='office is_partisan')),
                ('office_held_ctcl_id', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='we vote permanent id for this office held')),
                ('status', models.TextField(blank=True, default='', null=True, verbose_name='batch row action office held status')),
            ],
        ),
        migrations.DeleteModel(
            name='BatchRowActionElectedOffice',
        ),
        migrations.RemoveField(
            model_name='batchrowactioncontestoffice',
            name='elected_office_name',
        ),
        migrations.AddField(
            model_name='batchrowactioncontestoffice',
            name='office_held_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the office held'),
        ),
        migrations.AlterField(
            model_name='batchdescription',
            name='kind_of_batch',
            field=models.CharField(choices=[('MEASURE', 'Measure'), ('OFFICE_HELD', 'OfficeHeld'), ('CONTEST_OFFICE', 'ContestOffice'), ('CANDIDATE', 'Candidate'), ('IMPORT_BALLOT_ITEM', 'Ballot Returned'), ('IMPORT_POLLING_LOCATION', 'Map Point'), ('ORGANIZATION', 'Organization'), ('POSITION', 'Position'), ('POLITICIAN', 'Politician')], db_index=True, default='MEASURE', max_length=32),
        ),
        migrations.AlterField(
            model_name='batchheadertranslationsuggestion',
            name='kind_of_batch',
            field=models.CharField(choices=[('MEASURE', 'Measure'), ('OFFICE_HELD', 'OfficeHeld'), ('CONTEST_OFFICE', 'ContestOffice'), ('CANDIDATE', 'Candidate'), ('IMPORT_BALLOT_ITEM', 'Ballot Returned'), ('IMPORT_POLLING_LOCATION', 'Map Point'), ('ORGANIZATION', 'Organization'), ('POSITION', 'Position'), ('POLITICIAN', 'Politician')], default='MEASURE', max_length=32),
        ),
        migrations.AlterField(
            model_name='batchrowactioncandidate',
            name='ballotpedia_office_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ballotpedia office held integer id'),
        ),
        migrations.AlterField(
            model_name='batchrowtranslationmap',
            name='kind_of_batch',
            field=models.CharField(choices=[('MEASURE', 'Measure'), ('OFFICE_HELD', 'OfficeHeld'), ('CONTEST_OFFICE', 'ContestOffice'), ('CANDIDATE', 'Candidate'), ('IMPORT_BALLOT_ITEM', 'Ballot Returned'), ('IMPORT_POLLING_LOCATION', 'Map Point'), ('ORGANIZATION', 'Organization'), ('POSITION', 'Position'), ('POLITICIAN', 'Politician')], default='MEASURE', max_length=32),
        ),
    ]
