# Generated by Django 3.2.16 on 2023-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0006_auto_20230110_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessRepresentativesChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('batch_set_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('state_code', models.CharField(max_length=2, null=True)),
                ('retrieve_date_started', models.DateTimeField(null=True)),
                ('retrieve_date_completed', models.DateTimeField(null=True)),
                ('retrieve_timed_out', models.BooleanField(default=None, null=True)),
                ('retrieve_row_count', models.PositiveIntegerField(default=0)),
                ('politician_matching_date_started', models.DateTimeField(null=True)),
                ('politician_matching_date_completed', models.DateTimeField(null=True)),
                ('politician_matching_timed_out', models.BooleanField(default=None, null=True)),
                ('politician_matching_row_count', models.PositiveIntegerField(default=0)),
                ('politician_deduplication_date_started', models.DateTimeField(null=True)),
                ('politician_deduplication_date_completed', models.DateTimeField(null=True)),
                ('politician_deduplication_timed_out', models.BooleanField(default=None, null=True)),
                ('politician_deduplication_row_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='batchprocesslogentry',
            name='batch_process_representatives_chunk_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='batchset',
            name='batch_process_representatives_chunk_id',
            field=models.PositiveIntegerField(db_index=True, default=0, null=True),
        ),
    ]
