# Generated by Django 3.2.17 on 2023-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0007_auto_20230201_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='politician_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='politician_email2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='politician_email3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
