# Generated by Django 3.2.17 on 2023-02-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0008_auto_20230203_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='facebook_url2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='facebook_url3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='politician_phone_number2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batchrowactionpolitician',
            name='politician_phone_number3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchrowactionpolitician',
            name='politician_phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchrowactionpolitician',
            name='politician_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
