# Generated by Django 3.2.19 on 2023-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0009_auto_20230203_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrowactionpolitician',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender'),
        ),
    ]
