# Generated by Django 3.2.23 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0010_alter_batchrowactionpolitician_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrowactionorganization',
            name='organization_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='organization twitter username'),
        ),
        migrations.AlterField(
            model_name='batchrowactionposition',
            name='ballot_item_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for candidate, measure, or office'),
        ),
        migrations.AlterField(
            model_name='batchrowactionposition',
            name='speaker_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for org or person with position'),
        ),
    ]
