# Generated by Django 5.0.3 on 2024-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0011_auto_20240129_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactionorganization',
            name='organization_ballotpedia',
            field=models.URLField(blank=True, null=True, verbose_name='url of ballotpedia page'),
        ),
    ]
