# Generated by Django 5.0.3 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0012_batchrowactionorganization_organization_ballotpedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrowactionorganization',
            name='organization_wikipedia',
            field=models.URLField(blank=True, null=True, verbose_name='url of wikipedia page'),
        ),
    ]
