# Generated by Django 5.0.3 on 2024-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0013_batchrowactionorganization_organization_wikipedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchrowactionposition',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more info about this position'),
        ),
    ]
