# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0014_alter_batchrowactionposition_more_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdescription',
            name='source_uri',
            field=models.TextField(null=True, verbose_name='uri where data is coming from'),
        ),
        migrations.AlterField(
            model_name='batchrowactionballotitem',
            name='measure_url',
            field=models.TextField(null=True, verbose_name='url of measure'),
        ),
        migrations.AlterField(
            model_name='batchrowactioncandidate',
            name='candidate_contact_form_url',
            field=models.TextField(null=True, verbose_name='website url of candidate contact form'),
        ),
        migrations.AlterField(
            model_name='batchrowactioncandidate',
            name='candidate_url',
            field=models.TextField(null=True, verbose_name='website url of candidate'),
        ),
        migrations.AlterField(
            model_name='batchrowactionorganization',
            name='organization_contact_form_url',
            field=models.TextField(null=True, verbose_name='url of the organization contact form'),
        ),
        migrations.AlterField(
            model_name='batchrowactionorganization',
            name='organization_website',
            field=models.TextField(null=True, verbose_name='url of the endorsing organization'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='source_uri',
            field=models.TextField(null=True, verbose_name='uri where data is coming from'),
        ),
    ]
