# Generated by Django 5.0.13 on 2025-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_batches', '0018_alter_batchprocess_kind_of_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocess',
            name='kind_of_process',
            field=models.CharField(choices=[('ACTIVITY_NOTICE_PROCESS', 'Create, update, or schedule to send Activity Notices'), ('API_REFRESH_REQUEST', 'Make sure we have cached a recent return from a specific API'), ('AUGMENT_ANALYTICS_ACTION_WITH_ELECTION_ID', 'Add election id to AnalyticsAction'), ('AUGMENT_ANALYTICS_ACTION_WITH_FIRST_VISIT', 'Mark first AnalyticsAction per day'), ('CALCULATE_SITEWIDE_VOTER_METRICS', 'Sitewide voter metrics for all time'), ('CALCULATE_SITEWIDE_DAILY_METRICS', 'Sitewide daily metrics'), ('CALCULATE_SITEWIDE_ELECTION_METRICS', 'Sitewide election metrics'), ('CALCULATE_ORGANIZATION_DAILY_METRICS', 'Organization specific daily metrics'), ('CALCULATE_ORGANIZATION_ELECTION_METRICS', 'Organization specific election metrics'), ('DEDUPLICATION_SCRIPTS_CAMPAIGNX', 'Deduplication Scripts for CampaignX'), ('DEDUPLICATION_SCRIPTS_CANDIDATE', 'Deduplication Scripts for Candidate'), ('DEDUPLICATION_SCRIPTS_CHALLENGE', 'Deduplication Scripts for Challenge'), ('DEDUPLICATION_SCRIPTS_ORGANIZATION', 'Deduplication Scripts for Organization'), ('DEDUPLICATION_SCRIPTS_POLITICIAN', 'Deduplication Scripts for Politician'), ('GENERATE_VOTER_GUIDES', 'Generate voter guides'), ('MAINTENANCE_SCRIPTS_CAMPAIGNX', 'Maintenance Scripts for CampaignX'), ('MAINTENANCE_SCRIPTS_CANDIDATE', 'Maintenance Scripts for Candidate'), ('MAINTENANCE_SCRIPTS_CHALLENGE', 'Maintenance Scripts for Challenge'), ('MAINTENANCE_SCRIPTS_OFFICE', 'Maintenance Scripts for Office'), ('MAINTENANCE_SCRIPTS_OFFICE_HELD', 'Maintenance Scripts for Office Held'), ('MAINTENANCE_SCRIPTS_ORGANIZATION', 'Maintenance Scripts for Organization'), ('MAINTENANCE_SCRIPTS_POLITICIAN', 'Maintenance Scripts for Politician'), ('MAINTENANCE_SCRIPTS_POSITION', 'Maintenance Scripts for Position'), ('MAINTENANCE_SCRIPTS_REPRESENTATIVE', 'Maintenance Scripts for Representative'), ('MAINTENANCE_SCRIPTS_VOTER', 'Maintenance Scripts for Voter'), ('MATCH_POLITICIANS_TO_ORGANIZATIONS', 'Match politicians to organizations'), ('RETRIEVE_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', 'Retrieve Ballot Items from Map Points'), ('RETRIEVE_FROM_BALLOTPEDIA', 'Retrieve Data from Ballotpedia'), ('REFRESH_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', 'Refresh Ballot Items from BallotReturned Map Points'), ('REFRESH_BALLOT_ITEMS_FROM_VOTERS', 'Refresh Ballot Items from Voter Custom Addresses'), ('SEARCH_TWITTER_FOR_CANDIDATE_TWITTER_HANDLE', 'Search for Candidate Twitter Handles')], db_index=True, default='RETRIEVE_BALLOT_ITEMS_FROM_POLLING_LOCATIONS', max_length=50),
        ),
    ]
