# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkitem',
            name='candidate_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='bookmarkitem',
            name='contest_measure_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmarkitem',
            name='contest_measure_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='bookmarkitem',
            name='contest_office_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote permanent id'),
        ),
    ]
