# Generated by Django 5.0.3 on 2024-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickinfo',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more the full entry for this info'),
        ),
        migrations.AlterField(
            model_name='quickinfomaster',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more the full entry for this info'),
        ),
    ]
