# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='we_vote_id',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='party we_vote_id'),
        ),
    ]
