# Generated by Django 3.2.23 on 2024-01-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GooglebotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True, verbose_name='date requested')),
                ('request_url_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Request URL end string')),
                ('is_from_google', models.BooleanField(default=False, verbose_name="is remote address registered as Google's")),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote Address')),
                ('remote_dns', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote reverse DNS')),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
