# Generated by Django 5.0.9 on 2024-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenReplayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(null=True)),
                ('value', models.TextField(null=True)),
                ('selector', models.TextField(null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenReplaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors_count', models.PositiveIntegerField(null=True)),
                ('events_count', models.PositiveIntegerField(null=True)),
                ('pages_count', models.PositiveIntegerField(null=True)),
                ('project_id', models.CharField(max_length=255, null=True)),
                ('user_uuid', models.CharField(max_length=36, null=True)),
            ],
        ),
    ]
