# Generated by Django 5.0.13 on 2025-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_openreplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openreplayevent',
            name='base_referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='dom_building_time',
            field=models.PositiveIntegerField(blank=True, help_text='DOM building time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='dom_content_loaded_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='first_contentful_paint_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='first_paint_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='hesitation',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='load_time',
            field=models.PositiveIntegerField(blank=True, help_text='Load time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='response_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='speed_index',
            field=models.PositiveIntegerField(blank=True, help_text='Speed index in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='time_to_interactive',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='ttfb',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplayevent',
            name='visually_complete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='session_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='start_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Full User-Agent string', null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_browser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='openreplaysession',
            name='user_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openreplayevent',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='openreplayevent',
            name='selector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openreplayevent',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='openreplayevent',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openreplaysession',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
