# Generated by Django 3.2.25 on 2024-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTaskCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_constant', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('date_as_integer', models.PositiveIntegerField(db_index=True, null=True, verbose_name='YYYYMMDD of the action')),
                ('exact_time', models.DateTimeField(auto_now_add=True, verbose_name='date and time of action')),
                ('voter_id', models.PositiveIntegerField(default=None, null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerWeeklyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_week_date_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('voter_display_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('positions_saved', models.PositiveIntegerField(null=True)),
                ('positions_written_saved', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
