# Generated by Django 3.2.25 on 2024-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerweeklymetrics',
            old_name='positions_written_saved',
            new_name='candidates_created',
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='position_comments_saved',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='voter_date_unique_string',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='voter_guide_possibilities_created',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
