# Generated by Django 3.2.25 on 2024-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0002_auto_20240313_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='politicians_deduplicated',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
