# Generated by Django 3.2.25 on 2024-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0003_volunteerweeklymetrics_politicians_deduplicated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('team_description', models.TextField(null=True)),
                ('we_vote_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('team_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
