# Generated by Django 3.2.25 on 2024-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0004_volunteerteam_volunteerteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='politicians_augmented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='politicians_photo_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='politicians_requested_changes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='candidates_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='politicians_deduplicated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='position_comments_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='positions_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='voter_guide_possibilities_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
