# Generated by Django 3.2.25 on 2024-04-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0005_auto_20240407_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='duplicate_politician_analysis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='election_retrieve_started',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='match_candidates_to_politicians',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='twitter_bulk_retrieve',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
