# Generated by Django 5.0.3 on 2024-04-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0006_auto_20240407_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerteam',
            name='which_day_is_end_of_week',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='which_day_is_end_of_week',
            field=models.PositiveIntegerField(db_index=True, default=6),
        ),
    ]
