# Generated by Django 5.0.9 on 2024-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0007_volunteerteam_which_day_is_end_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='which_day_is_end_of_week',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddIndex(
            model_name='volunteerweeklymetrics',
            index=models.Index(fields=['voter_we_vote_id', 'which_day_is_end_of_week', 'end_of_week_date_integer'], name='vol_weekly_index'),
        ),
    ]
