# Generated by Django 5.0.9 on 2024-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0008_alter_volunteerweeklymetrics_voter_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerweeklymetrics',
            name='voter_date_unique_string',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='volunteerweeklymetrics',
            index=models.Index(fields=['voter_date_unique_string'], name='voter_date_unique_string'),
        ),
    ]
