# Generated by Django 5.0.9 on 2024-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0009_alter_volunteerweeklymetrics_voter_date_unique_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='date_last_updated_as_integer',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
