# Generated by Django 5.0.13 on 2025-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_task', '0010_volunteerweeklymetrics_date_last_updated_as_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='organizations_augmented',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerweeklymetrics',
            name='organizations_deduplicated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
