# Generated by Django 3.2.17 on 2023-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wevoteimage',
            name='representative_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
