# Generated by Django 3.2.17 on 2023-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_wevoteimage_representative_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wevoteimage',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
