# Generated by Django 3.2.18 on 2023-06-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_wevoteimage_politician_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wevoteimage',
            name='kind_of_image_politician_uploaded_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wevoteimage',
            name='politician_uploaded_profile_image_url_https',
            field=models.TextField(blank=True, null=True),
        ),
    ]
