# Generated by Django 3.2.20 on 2023-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20230606_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='wevoteimage',
            name='kind_of_image_organization_uploaded_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wevoteimage',
            name='organization_uploaded_profile_image_url_https',
            field=models.TextField(blank=True, null=True),
        ),
    ]
