# Generated by Django 5.0.3 on 2024-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20230806_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wevoteimage',
            name='is_active_version',
            field=models.BooleanField(db_index=True, default=False, verbose_name='True if image is newest'),
        ),
        migrations.AddIndex(
            model_name='wevoteimage',
            index=models.Index(fields=['campaignx_we_vote_id', 'candidate_we_vote_id', 'organization_we_vote_id', 'politician_we_vote_id', 'representative_we_vote_id', 'issue_we_vote_id', 'voter_we_vote_id'], name='image_we_vote_ids_index'),
        ),
    ]
