# Generated by Django 5.0.3 on 2024-07-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_alter_wevoteimage_is_active_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wevoteimage',
            name='is_active_version',
            field=models.BooleanField(default=False, verbose_name='True if image is newest'),
        ),
        migrations.AddIndex(
            model_name='wevoteimage',
            index=models.Index(fields=['candidate_we_vote_id', '-date_image_saved'], name='candidate_index'),
        ),
        migrations.AddIndex(
            model_name='wevoteimage',
            index=models.Index(fields=['is_active_version'], name='is_active_version'),
        ),
    ]
