# Generated by Django 3.2.23 on 2024-02-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_custom_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_formatted_url',
            field=models.TextField(blank=True, null=True, verbose_name='item formatted url'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_image',
            field=models.TextField(blank=True, null=True, verbose_name='image url for searched item'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_link',
            field=models.TextField(blank=True, null=True, verbose_name='url where searched item pointing'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_meta_tags_description',
            field=models.TextField(blank=True, null=True, verbose_name='searched item meta tags description'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='searched item snippet'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='item_title',
            field=models.TextField(blank=True, null=True, verbose_name='searched item title'),
        ),
        migrations.AlterField(
            model_name='googlesearchuser',
            name='search_request_url',
            field=models.TextField(blank=True, null=True, verbose_name='search request url'),
        ),
    ]
