# Generated by Django 3.2.16 on 2023-01-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politician_twitter_handle2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_twitter_handle3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_twitter_handle4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_twitter_handle5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politician_twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
