# Generated by Django 3.2.16 on 2023-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0002_auto_20230104_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_politician_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name exactly as received from ballotpedia'),
        ),
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_politician_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of politician on ballotpedia'),
        ),
        migrations.AddField(
            model_name='politician',
            name='facebook_url',
            field=models.TextField(blank=True, null=True, verbose_name='facebook url of candidate'),
        ),
        migrations.AddField(
            model_name='politician',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False, verbose_name='facebook url is broken'),
        ),
        migrations.AddField(
            model_name='politician',
            name='instagram_followers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name="count of candidate's instagram followers"),
        ),
        migrations.AddField(
            model_name='politician',
            name='instagram_handle',
            field=models.TextField(blank=True, null=True, verbose_name="politician's instagram handle"),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_contact_form_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='website url of contact form'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text description of this organization from twitter.'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_followers_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='number of twitter followers'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='candidate location from twitter'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='candidate plain text name from twitter'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_profile_background_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='tile-able background from twitter'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_profile_banner_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='profile banner image from twitter'),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached url of candidate profile image from twitter'),
        ),
        migrations.AddField(
            model_name='politician',
            name='vote_usa_profile_image_url_https',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('N', 'Nonbinary'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politician_email_address',
            field=models.CharField(max_length=255, null=True, verbose_name='politician email address'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted large image url'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted medium image url'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True, verbose_name='we vote hosted tiny image url'),
        ),
    ]
