# Generated by Django 3.2.16 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0003_auto_20230106_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='date_last_updated_from_candidate',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_handle2_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_handle_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='wikipedia_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
