# Generated by Django 3.2.16 on 2023-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0004_auto_20230126_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politician_url2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_url3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_url4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_url5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politician_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
