# Generated by Django 3.2.16 on 2023-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0005_auto_20230128_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politician_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_email2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_email3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politician_email_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
