# Generated by Django 3.2.17 on 2023-02-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0006_auto_20230201_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='facebook_url2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='facebook_url2_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='facebook_url3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='facebook_url3_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_phone_number2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_phone_number3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politician_phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
