# Generated by Django 3.2.17 on 2023-02-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0007_auto_20230203_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded'), ('VOTE_USA', 'Vote-USA')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='twitter_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='twitter id'),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_facebook_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_facebook_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_facebook_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_twitter_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_twitter_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_twitter_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_uploaded_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_uploaded_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_uploaded_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_vote_usa_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_vote_usa_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_vote_usa_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
    ]
