# Generated by Django 3.2.17 on 2023-02-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0008_auto_20230208_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticiansArePossibleDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician1_we_vote_id', models.CharField(max_length=255, null=True)),
                ('politician2_we_vote_id', models.CharField(max_length=255, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
