# Generated by Django 3.2.18 on 2023-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0009_politiciansarepossibleduplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2019',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2020',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2021',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2023',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2024',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2025',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_battleground_race_2026',
            field=models.BooleanField(default=False),
        ),
    ]
