# Generated by Django 3.2.18 on 2023-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0010_auto_20230306_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianSEOFriendlyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician_we_vote_id', models.CharField(max_length=255, null=True)),
                ('politician_name', models.CharField(max_length=255)),
                ('base_pathname_string', models.CharField(max_length=255, null=True)),
                ('pathname_modifier', models.CharField(max_length=10, null=True)),
                ('final_pathname_string', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='politician',
            name='seo_friendly_path',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
