# Generated by Django 3.2.18 on 2023-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0011_auto_20230320_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='seo_friendly_path_date_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
