# Generated by Django 3.2.18 on 2023-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0012_politician_seo_friendly_path_date_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='linked_campaignx_we_vote_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
