# Generated by Django 3.2.18 on 2023-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0013_politician_linked_campaignx_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='linked_campaignx_we_vote_id_date_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
