# Generated by Django 3.2.18 on 2023-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0014_politician_linked_campaignx_we_vote_id_date_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='supporters_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
