# Generated by Django 3.2.18 on 2023-06-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0015_politician_supporters_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_politician_photo_original_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='instagram_followers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name="count of politician's instagram followers"),
        ),
        migrations.AlterField(
            model_name='politician',
            name='twitter_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='politician location from twitter'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='twitter_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='politician plain text name from twitter'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='twitter_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached url of politician profile image from twitter'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='vote_usa_politician_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Vote USA permanent id for this politician'),
        ),
    ]
