# Generated by Django 3.2.19 on 2023-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0016_auto_20230606_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='google_civic_name_alternates_generated',
            field=models.BooleanField(default=False),
        ),
    ]
