# Generated by Django 3.2.19 on 2023-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0017_politician_google_civic_name_alternates_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='photo_url_from_vote_usa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
