# Generated by Django 3.2.19 on 2023-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0018_politician_photo_url_from_vote_usa'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ocd_id_state_mismatch_found',
            field=models.BooleanField(default=False),
        ),
    ]
