# Generated by Django 3.2.19 on 2023-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0019_politician_ocd_id_state_mismatch_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='seo_friendly_path_needs_regeneration',
            field=models.BooleanField(default=False),
        ),
    ]
