# Generated by Django 3.2.19 on 2023-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0020_politician_seo_friendly_path_needs_regeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballot_guide_official_statement',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='official candidate statement from ballot guide'),
        ),
    ]
