# Generated by Django 3.2.19 on 2023-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0021_politician_ballot_guide_official_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='gender_likelihood',
            field=models.CharField(choices=[('PolDataMgr', 'Political Data Mgr'), ('Politician', 'Politician Provided'), ('GuessHigh', 'Gender Guesser High Likelihood'), ('GuessLow', 'Gender Guesser Low Likelihood'), ('', '')], default='', max_length=11, verbose_name='gender guess likelihood'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Nonbinary'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='gender'),
        ),
    ]
