# Generated by Django 3.2.23 on 2023-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0022_auto_20230720_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='profile_image_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='linked_campaignx_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
