# Generated by Django 3.2.23 on 2023-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0023_auto_20231216_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='profile_image_background_color_needed',
            field=models.BooleanField(null=True),
        ),
    ]
