# Generated by Django 3.2.23 on 2024-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0024_politician_profile_image_background_color_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote ballotpedia profile photo'),
        ),
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached profile image from ballotpedia'),
        ),
        migrations.AddField(
            model_name='politician',
            name='linkedin_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote linkedin profile photo'),
        ),
        migrations.AddField(
            model_name='politician',
            name='linkedin_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached candidate profile image from linkedin'),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_ballotpedia_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_ballotpedia_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_ballotpedia_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_linkedin_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_linkedin_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_linkedin_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_wikipedia_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_wikipedia_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='we_vote_hosted_profile_wikipedia_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='wikipedia_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote wikipedia profile photo'),
        ),
        migrations.AddField(
            model_name='politician',
            name='wikipedia_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached candidate profile image from wikipedia'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('BALLOTPEDIA', 'Ballotpedia'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded'), ('VOTE_USA', 'Vote-USA'), ('WIKIPEDIA', 'Wikipedia')], default='UNKNOWN', max_length=11),
        ),
    ]
