# Generated by Django 3.2.25 on 2024-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0025_auto_20240210_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('politician_we_vote_id', models.CharField(max_length=255)),
                ('changed_by_name', models.CharField(default=None, max_length=255, null=True)),
                ('changed_by_voter_we_vote_id', models.CharField(default=None, max_length=255, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('log_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
                ('is_ballotpedia_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_ballotpedia_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_facebook_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_facebook_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_from_twitter', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_linkedin_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_linkedin_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_official_statement_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_official_statement_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_photo_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_photo_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_politician_analysis_done', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_politician_url_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_politician_url_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_twitter_handle_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_twitter_handle_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_website_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_website_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_wikipedia_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_wikipedia_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_withdrawal_date_added', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_withdrawal_date_removed', models.BooleanField(db_index=True, default=None, null=True)),
                ('kind_of_log_entry', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_analysis_done',
            field=models.BooleanField(default=False),
        ),
    ]
