# Generated by Django 5.0.3 on 2024-05-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0026_auto_20240407_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_photo_url_is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
