# Generated by Django 5.0.3 on 2024-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0027_politician_ballotpedia_photo_url_is_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_photo_url_is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
