# Generated by Django 5.0.3 on 2024-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0028_politician_ballotpedia_photo_url_is_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPoliticianLinkByPolitician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_politician_we_vote_id', models.CharField(max_length=255, null=True)),
                ('recommended_politician_we_vote_id', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
