# Generated by Django 5.0.3 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0029_recommendedpoliticianlinkbypolitician'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='wikipedia_photo_does_not_exist',
            field=models.BooleanField(default=False),
        ),
    ]
