# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0030_politician_wikipedia_photo_does_not_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='politician_contact_form_url',
            field=models.TextField(null=True, verbose_name='website url of contact form'),
        ),
    ]
