# Generated by Django 5.0.3 on 2024-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0031_alter_politician_politician_contact_form_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ballotpedia_candidate_links_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
