# Generated by Django 5.0.3 on 2024-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0032_politician_ballotpedia_candidate_links_retrieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='opposers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='politician',
            name='organization_and_manual_intervention_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='organization_might_be_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_ultimate_election_date',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
