# Generated by Django 5.0.3 on 2024-07-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0034_alter_politician_we_vote_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician',
            old_name='organization_and_manual_intervention_needed',
            new_name='organization_manual_intervention_needed',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='organization_might_be_needed',
        ),
        migrations.AddField(
            model_name='politician',
            name='organization_analysis_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='organization_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='politician_has_two_linked_organizations',
            field=models.BooleanField(default=False),
        ),
    ]
