# Generated by Django 5.0.3 on 2024-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0035_rename_organization_and_manual_intervention_needed_politician_organization_manual_intervention_neede'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='follow_organization_analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='follow_organization_intervention_needed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
