# Generated by Django 5.0.9 on 2024-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0036_politician_follow_organization_analysis_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='date_ultimate_election_last_updated_from_candidate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
