# Generated by Django 5.0.13 on 2025-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0038_politician_bluesky_handle_politician_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='linked_campaignx_we_vote_id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
