# Generated by Django 5.0.13 on 2025-10-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0039_politician_linked_campaignx_we_vote_id_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='is_claimed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
