# Generated by Django 5.0.13 on 2025-10-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0040_politician_is_claimed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticianSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('date_email_invite_sent', models.DateTimeField(db_index=True, null=True)),
                ('date_imported', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('date_sms_invite_sent', models.DateTimeField(db_index=True, null=True)),
                ('email_invite_sent', models.BooleanField(default=False)),
                ('email_ownership_is_verified', models.BooleanField(default=False)),
                ('email_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('invited_by_voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('normalized_sms_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('politician_name', models.CharField(default=None, max_length=255, null=True)),
                ('politician_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('sms_invite_sent', models.BooleanField(default=False)),
                ('sms_ownership_is_verified', models.BooleanField(default=False)),
                ('sms_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stance', models.CharField(choices=[('SUPPORT', 'Supports'), ('INFO_ONLY', 'Information only'), ('OPPOSE', 'Opposes')], db_index=True, default='INFO_ONLY', max_length=15)),
                ('supporter_name', models.CharField(default=None, max_length=255, null=True)),
                ('supporter_endorsement', models.TextField(null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(null=True)),
            ],
        ),
    ]
