# Generated by Django 5.0.13 on 2025-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0041_politiciansupporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='linked_campaignx_we_vote_id_verified_in_campaignx',
            field=models.BooleanField(default=False),
        ),
    ]
