# Generated by Django 5.0.13 on 2025-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0042_politician_linked_campaignx_we_vote_id_verified_in_campaignx'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='threads_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicianchangelog',
            name='is_threads_handle_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='politicianchangelog',
            name='is_threads_handle_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
