# Generated by Django 5.0.13 on 2025-11-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0044_deduplicationneededforstatetoday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='tag_link',
        ),
        migrations.RemoveField(
            model_name='politiciantaglinkdisputed',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='politiciantaglinkdisputed',
            name='tag',
        ),
        migrations.DeleteModel(
            name='PoliticianTagLink',
        ),
        migrations.DeleteModel(
            name='PoliticianTagLinkDisputed',
        ),
    ]
