# Generated by Django 5.0.13 on 2026-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0045_remove_politician_tag_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='is_claimed_profile_analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politician',
            name='is_claimed_profile_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
