# Generated by Django 5.0.13 on 2026-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0046_politician_is_claimed_profile_analysis_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiciansupporter',
            name='added_by_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='added_by_voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='added_via',
            field=models.CharField(choices=[('IMPORT_FROM_CSV', 'CSV import'), ('IMPORT_FROM_TEXT_LIST', 'Text import'), ('MANUAL_ENTRY', 'Manual entry')], db_index=True, default='MANUAL_ENTRY', max_length=24),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='date_supporter_opted_out',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='supporter_email_subscription_secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='supporter_opted_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politiciansupporter',
            name='voter_email_subscription_secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
