# Generated by Django 5.2.16 on 2026-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politician', '0047_politiciansupporter_added_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='politician_email_subscription_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
