# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_alter_measurecampaign_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmeasuresarenotduplicates',
            name='contest_measure1_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='first contest measure we are tracking'),
        ),
        migrations.AlterField(
            model_name='contestmeasuresarenotduplicates',
            name='contest_measure2_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='second contest measure we are tracking'),
        ),
        migrations.AlterField(
            model_name='measurecampaign',
            name='we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id'),
        ),
    ]
