# Generated by Django 5.0.8 on 2024-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_alter_contestmeasuresarenotduplicates_contest_measure1_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestmeasure',
            name='ballotpedia_measure_name',
            field=models.TextField(blank=True, null=True, verbose_name='ballotpedia measure name'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='ballotpedia_measure_url',
            field=models.TextField(blank=True, null=True, verbose_name='ballotpedia url of measure'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='google_civic_measure_title',
            field=models.TextField(blank=True, null=True, verbose_name='measure name exactly as received from google civic'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='google_civic_measure_title2',
            field=models.TextField(blank=True, null=True, verbose_name='measure name from google civic alternative'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='google_civic_measure_title3',
            field=models.TextField(blank=True, null=True, verbose_name='measure name from google civic alternative'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='google_civic_measure_title4',
            field=models.TextField(blank=True, null=True, verbose_name='measure name from google civic alternative'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='google_civic_measure_title5',
            field=models.TextField(blank=True, null=True, verbose_name='measure name from google civic alternative'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='measure_title',
            field=models.TextField(verbose_name='measure title'),
        ),
        migrations.AlterField(
            model_name='contestmeasure',
            name='measure_url',
            field=models.TextField(null=True, verbose_name='measure details url'),
        ),
    ]
