# Generated by Django 5.0.13 on 2026-03-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0004_alter_contestmeasure_ballotpedia_measure_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMeasuresArePossibleDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_measure1_we_vote_id', models.CharField(max_length=255, null=True)),
                ('contest_measure2_we_vote_id', models.CharField(max_length=255, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contestmeasuresarenotduplicates',
            name='contest_measure1_we_vote_id',
            field=models.CharField(max_length=255, null=True, verbose_name='first contest measure we are tracking'),
        ),
        migrations.AlterField(
            model_name='contestmeasuresarenotduplicates',
            name='contest_measure2_we_vote_id',
            field=models.CharField(max_length=255, null=True, verbose_name='second contest measure we are tracking'),
        ),
    ]
