# Generated by Django 3.2.16 on 2023-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_vote_id', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id for this office held')),
                ('office_held_name', models.CharField(max_length=255, verbose_name='name of the office held')),
                ('office_held_name_es', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the office held in Spanish')),
                ('google_civic_office_held_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='office_held name exactly as received from google civic')),
                ('google_civic_election_id', models.PositiveIntegerField(default=0, verbose_name='google civic election id')),
                ('ocd_division_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ocd division id')),
                ('maplight_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='maplight unique identifier')),
                ('ballotpedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ballotpedia unique identifier')),
                ('wikipedia_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='wikipedia unique identifier')),
                ('number_elected', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic number of candidates who will be elected')),
                ('state_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='state this office_held serves')),
                ('primary_party', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('district_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='district name')),
                ('district_scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district scope')),
                ('district_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic district id')),
                ('contest_level0', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 0')),
                ('contest_level1', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 1')),
                ('contest_level2', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic level, option 2')),
                ('electorate_specifications', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('special', models.CharField(blank=True, max_length=255, null=True, verbose_name='google civic primary party')),
                ('ctcl_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='ctcl uuid')),
                ('office_held_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='office_held description')),
                ('office_held_description_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='office_held description in Spanish')),
                ('office_held_is_partisan', models.BooleanField(default=False, verbose_name='office_held is_partisan')),
            ],
        ),
    ]
