# Generated by Django 3.2.16 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestOfficeToOfficeHeldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_office_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('office_held_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('contest_office_year', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfficesHeldForLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_retrieved', models.DateField(null=True)),
                ('office_held_name_01', models.CharField(max_length=255, null=True)),
                ('office_held_name_02', models.CharField(max_length=255, null=True)),
                ('office_held_name_03', models.CharField(max_length=255, null=True)),
                ('office_held_name_04', models.CharField(max_length=255, null=True)),
                ('office_held_name_05', models.CharField(max_length=255, null=True)),
                ('office_held_name_06', models.CharField(max_length=255, null=True)),
                ('office_held_name_07', models.CharField(max_length=255, null=True)),
                ('office_held_name_08', models.CharField(max_length=255, null=True)),
                ('office_held_name_09', models.CharField(max_length=255, null=True)),
                ('office_held_name_10', models.CharField(max_length=255, null=True)),
                ('office_held_name_11', models.CharField(max_length=255, null=True)),
                ('office_held_name_12', models.CharField(max_length=255, null=True)),
                ('office_held_name_13', models.CharField(max_length=255, null=True)),
                ('office_held_name_14', models.CharField(max_length=255, null=True)),
                ('office_held_name_15', models.CharField(max_length=255, null=True)),
                ('office_held_name_16', models.CharField(max_length=255, null=True)),
                ('office_held_name_17', models.CharField(max_length=255, null=True)),
                ('office_held_name_18', models.CharField(max_length=255, null=True)),
                ('office_held_name_19', models.CharField(max_length=255, null=True)),
                ('office_held_name_20', models.CharField(max_length=255, null=True)),
                ('office_held_name_21', models.CharField(max_length=255, null=True)),
                ('office_held_name_22', models.CharField(max_length=255, null=True)),
                ('office_held_name_23', models.CharField(max_length=255, null=True)),
                ('office_held_name_24', models.CharField(max_length=255, null=True)),
                ('office_held_name_25', models.CharField(max_length=255, null=True)),
                ('office_held_name_26', models.CharField(max_length=255, null=True)),
                ('office_held_name_27', models.CharField(max_length=255, null=True)),
                ('office_held_name_28', models.CharField(max_length=255, null=True)),
                ('office_held_name_29', models.CharField(max_length=255, null=True)),
                ('office_held_name_30', models.CharField(max_length=255, null=True)),
                ('office_held_we_vote_id_01', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_02', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_03', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_04', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_05', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_06', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_07', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_08', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_09', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_10', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_11', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_12', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_13', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_14', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_15', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_16', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_17', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_18', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_19', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_20', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_21', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_22', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_23', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_24', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_25', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_26', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_27', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_28', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_29', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('office_held_we_vote_id_30', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('polling_location_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
                ('voter_we_vote_id', models.CharField(default=None, max_length=255, null=True)),
                ('years_retrieved_flags', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='ballotpedia_id',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='contest_level0',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='contest_level1',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='contest_level2',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='ctcl_uuid',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='electorate_specifications',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='google_civic_election_id',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='maplight_id',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='special',
        ),
        migrations.RemoveField(
            model_name='officeheld',
            name='wikipedia_id',
        ),
        migrations.AddField(
            model_name='officeheld',
            name='google_civic_office_held_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='google_civic_office_held_name3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_level0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_level1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_level2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_role0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_role1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_role2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='race_office_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='year_with_data_2023',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='year_with_data_2024',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='year_with_data_2025',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='year_with_data_2026',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='officeheld',
            name='google_civic_office_held_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officeheld',
            name='number_elected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
