# Generated by Django 3.2.16 on 2023-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0002_auto_20230126_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesheldforlocation',
            name='years_retrieved_flags',
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='date_last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='year_with_data_2023',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='year_with_data_2024',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='year_with_data_2025',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='year_with_data_2026',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
