# Generated by Django 3.2.17 on 2023-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0003_auto_20230201_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2022',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2023',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2024',
            field=models.BooleanField(default=False),
        ),
    ]
