# Generated by Django 3.2.18 on 2023-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0004_auto_20230222_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2019',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2020',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2021',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2025',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_battleground_race_2026',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
