# Generated by Django 3.2.18 on 2023-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0005_auto_20230306_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='office_held_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
