# Generated by Django 3.2.18 on 2023-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0006_officeheld_office_held_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='office_held_facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
