# Generated by Django 3.2.18 on 2023-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0007_auto_20230311_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesheldforlocation',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='latitude returned from Google'),
        ),
        migrations.AddField(
            model_name='officesheldforlocation',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='longitude returned from Google'),
        ),
    ]
