# Generated by Django 3.2.18 on 2023-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0008_auto_20230423_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeheld',
            name='office_held_description',
            field=models.TextField(blank=True, null=True, verbose_name='office_held description'),
        ),
        migrations.AlterField(
            model_name='officeheld',
            name='office_held_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='office_held description in Spanish'),
        ),
    ]
