# Generated by Django 3.2.19 on 2023-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0009_auto_20230531_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='ocd_id_state_mismatch_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='ocd_id_state_mismatch_found',
            field=models.BooleanField(default=False),
        ),
    ]
