# Generated by Django 3.2.20 on 2023-08-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0010_auto_20230629_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='is_us_national_house',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='officeheld',
            name='is_us_national_senate',
            field=models.BooleanField(null=True),
        ),
    ]
