# Generated by Django 5.0.13 on 2026-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_held', '0011_auto_20230827_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeheld',
            name='office_explanation_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
