# Generated by Django 3.2.16 on 2023-01-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='is_battleground_race_cached_in_candidates',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
