# Generated by Django 3.2.16 on 2023-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_contestoffice_is_battleground_race_cached_in_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestoffice',
            name='elected_office_name',
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_held_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the office held'),
        ),
    ]
