# Generated by Django 3.2.17 on 2023-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20230110_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='office_held_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
    ]
