# Generated by Django 3.2.18 on 2023-03-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_contestoffice_office_held_we_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestoffice',
            name='is_battleground_race_cached_in_candidates',
        ),
    ]
