# Generated by Django 3.2.18 on 2023-03-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_remove_contestoffice_is_battleground_race_cached_in_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='is_battleground_race_spread_to_all_objects',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
