# Generated by Django 3.2.18 on 2023-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_contestoffice_is_battleground_race_spread_to_all_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_held_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='office_held description'),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_held_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='office_held description in Spanish'),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_held_name_es',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name of the office held in Spanish'),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_twitter_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contestoffice',
            name='office_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
