# Generated by Django 3.2.18 on 2023-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20230419_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestoffice',
            name='office_held_description',
            field=models.TextField(blank=True, null=True, verbose_name='office_held description'),
        ),
        migrations.AlterField(
            model_name='contestoffice',
            name='office_held_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='office_held description in Spanish'),
        ),
    ]
