# Generated by Django 3.2.19 on 2023-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20230531_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='election_date_as_integer',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
