# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_contestoffice_election_date_as_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestofficesarenotduplicates',
            name='contest_office1_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='first contest office we are tracking'),
        ),
        migrations.AlterField(
            model_name='contestofficesarenotduplicates',
            name='contest_office2_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='second contest office we are tracking'),
        ),
        migrations.AlterField(
            model_name='contestofficevisitingotherelection',
            name='contest_office_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='contest office we are tracking'),
        ),
    ]
