# Generated by Django 5.0.8 on 2024-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_alter_contestofficesarenotduplicates_contest_office1_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestoffice',
            name='we_vote_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id for this contest office'),
        ),
        migrations.AddIndex(
            model_name='contestoffice',
            index=models.Index(fields=['we_vote_id'], name='contest_office_id_index'),
        ),
    ]
