# Generated by Django 5.0.13 on 2026-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_alter_contestoffice_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestoffice',
            name='office_explanation_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OfficeExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('office_explanation', models.TextField(null=True)),
                ('office_explanation_name', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=2, null=True)),
                ('video_url_horizontal', models.TextField(null=True)),
                ('video_url_square', models.TextField(null=True)),
                ('video_url_vertical', models.TextField(null=True)),
                ('we_vote_id', models.CharField(default=None, max_length=255, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['we_vote_id'], name='office_explanation_index')],
            },
        ),
    ]
