# Generated by Django 3.2.13 on 2022-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='voter we vote id person 1')),
                ('viewee_voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='voter we vote id person 2')),
                ('mutual_friend_voter_we_vote_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mutual_friend_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mutual_friend_display_name_exists', models.BooleanField(db_index=True, default=False)),
                ('mutual_friend_we_vote_hosted_profile_image_url_medium', models.TextField(blank=True, null=True)),
                ('mutual_friend_profile_image_exists', models.BooleanField(db_index=True, default=False)),
                ('viewer_to_mutual_friend_friend_count', models.PositiveSmallIntegerField(null=True)),
                ('viewee_to_mutual_friend_friend_count', models.PositiveSmallIntegerField(null=True)),
                ('date_last_changed', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='currentfriend',
            name='mutual_friend_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currentfriend',
            name='mutual_friend_count_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='currentfriend',
            name='mutual_friend_preview_list_serialized',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currentfriend',
            name='mutual_friend_preview_list_update_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suggestedfriend',
            name='mutual_friend_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='suggestedfriend',
            name='mutual_friend_count_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suggestedfriend',
            name='mutual_friend_preview_list_serialized',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='suggestedfriend',
            name='mutual_friend_preview_list_update_needed',
            field=models.BooleanField(default=True),
        ),
    ]
