# Generated by Django 3.2.13 on 2022-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20220619_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationvoterlink',
            name='mutual_friend_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='friendinvitationvoterlink',
            name='mutual_friend_count_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='friendinvitationvoterlink',
            name='mutual_friend_preview_list_serialized',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='friendinvitationvoterlink',
            name='mutual_friend_preview_list_update_needed',
            field=models.BooleanField(default=True),
        ),
    ]
