# Generated by Django 3.2.13 on 2022-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20220623_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationemaillink',
            name='invited_friend_accepted_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendinvitationvoterlink',
            name='invited_friend_accepted_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
