# Generated by Django 3.2.23 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_auto_20220707_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitationtwitterlink',
            name='recipient_twitter_handle',
            field=models.CharField(max_length=255, verbose_name='twitter username'),
        ),
    ]
