# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_alter_friendinvitationtwitterlink_recipient_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendinvitationemaillink',
            name='recipient_email_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='email we vote id for recipient'),
        ),
        migrations.AlterField(
            model_name='friendinvitationemaillink',
            name='secret_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='secret key to accept invite'),
        ),
        migrations.AlterField(
            model_name='friendinvitationemaillink',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
        migrations.AlterField(
            model_name='friendinvitationtwitterlink',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
    ]
