# Generated by Django 5.0.8 on 2024-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_alter_friendinvitationemaillink_recipient_email_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currentfriend',
            index=models.Index(fields=['viewer_voter_we_vote_id', 'viewee_voter_we_vote_id'], name='curr_viewer_viewee'),
        ),
        migrations.AddIndex(
            model_name='friendinvitationvoterlink',
            index=models.Index(fields=['recipient_voter_we_vote_id', 'invitation_status', 'deleted'], name='recipient_index'),
        ),
        migrations.AddIndex(
            model_name='friendinvitationvoterlink',
            index=models.Index(fields=['sender_voter_we_vote_id', 'invitation_status', 'deleted'], name='sender_index'),
        ),
        migrations.AddIndex(
            model_name='suggestedfriend',
            index=models.Index(fields=['viewer_voter_we_vote_id', 'viewee_voter_we_vote_id'], name='sugg_viewer_viewee'),
        ),
    ]
