# Generated by Django 3.2.13 on 2022-05-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='flickr_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='go_fund_me_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='vimeo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
