# Generated by Django 5.0.13 on 2026-02-25 15:52

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, BtreeGistExtension

class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),  # Enables pg_trgm extension
        BtreeGistExtension(),  # For GiST index support
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS candidate_name_trgm_idx ON candidate_candidatecampaign USING gist(candidate_name gist_trgm_ops);",
            "DROP INDEX IF EXISTS candidate_name_trgm_idx;"
        ),

    ]