# Generated by Django 3.2.16 on 2023-01-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20220522_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='is_battleground_race',
            field=models.BooleanField(default=False),
        ),
    ]
