# Generated by Django 3.2.16 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidatecampaign_ballotpedia_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='twitter_handle2_updates_failing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='wikipedia_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
