# Generated by Django 3.2.16 on 2023-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20230126_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='twitter_handle_updates_failing',
            field=models.BooleanField(default=False),
        ),
    ]
