# Generated by Django 3.2.17 on 2023-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidatecampaign_twitter_handle_updates_failing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='facebook_url_is_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='instagram_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
