# Generated by Django 3.2.18 on 2023-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidatecampaign_office_held_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='seo_friendly_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
