# Generated by Django 3.2.18 on 2023-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_candidatecampaign_seo_friendly_path_date_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='linked_campaignx_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='linked_campaignx_we_vote_id_date_last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
