# Generated by Django 3.2.18 on 2023-05-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidatecampaign_supporters_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='candidate name'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_twitter_handle',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_twitter_handle2',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_twitter_handle3',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_year',
            field=models.PositiveIntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='google_civic_candidate_name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='candidate name exactly as received from google civic'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='google_civic_candidate_name2',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='candidate name exactly as received from google civic'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='google_civic_candidate_name3',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='candidate name exactly as received from google civic'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='instagram_handle',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name="candidate's instagram handle"),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='vote_usa_politician_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True, verbose_name='Vote USA permanent id for this candidate'),
        ),
    ]
