# Generated by Django 3.2.18 on 2023-06-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_auto_20230524_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='district_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district name'),
        ),
    ]
