# Generated by Django 3.2.19 on 2023-06-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_candidatecampaign_district_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='ocd_id_state_mismatch_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='ocd_id_state_mismatch_found',
            field=models.BooleanField(default=False),
        ),
    ]
