# Generated by Django 3.2.19 on 2023-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_auto_20230629_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='ballot_guide_official_statement',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='official candidate statement from ballot guide'),
        ),
    ]
