# Generated by Django 3.2.20 on 2023-08-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_alter_candidatecampaign_ballot_guide_official_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='representative_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
