# Generated by Django 3.2.23 on 2023-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_candidatecampaign_representative_we_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='politician_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote politician id'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='seo_friendly_path',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
