# Generated by Django 3.2.23 on 2023-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_auto_20231216_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='profile_image_background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
