# Generated by Django 3.2.23 on 2024-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_candidatecampaign_profile_image_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='candidate_analysis_done',
            field=models.BooleanField(default=False),
        ),
    ]
