# Generated by Django 3.2.23 on 2024-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_candidatecampaign_candidate_analysis_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('candidate_we_vote_id', models.CharField(max_length=255)),
                ('changed_by_name', models.CharField(default=None, max_length=255, null=True)),
                ('changed_by_voter_we_vote_id', models.CharField(default=None, max_length=255, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('log_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='date last changed')),
                ('google_civic_election_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('is_from_twitter', models.BooleanField(db_index=True, default=False, null=True)),
                ('kind_of_log_entry', models.CharField(db_index=True, default=None, max_length=50, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CandidateLogEntry',
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='linkedin_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached candidate profile image from linkedin'),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_ballotpedia_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_ballotpedia_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_ballotpedia_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_linkedin_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_linkedin_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_linkedin_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_wikipedia_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_wikipedia_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='we_vote_hosted_profile_wikipedia_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='wikipedia_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached candidate profile image from wikipedia'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='ballotpedia_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote ballotpedia profile photo'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='ballotpedia_profile_image_url_https',
            field=models.TextField(blank=True, null=True, verbose_name='locally cached profile image from ballotpedia'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='linkedin_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote linkedin profile photo'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='profile_image_type_currently_active',
            field=models.CharField(choices=[('BALLOTPEDIA', 'Ballotpedia'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('UNKNOWN', 'Unknown'), ('UPLOADED', 'Uploaded'), ('VOTE_USA', 'Vote-USA'), ('WIKIPEDIA', 'Wikipedia')], default='UNKNOWN', max_length=11),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='wikipedia_photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='url of remote wikipedia profile photo'),
        ),
    ]
