# Generated by Django 3.2.23 on 2024-02-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_auto_20240210_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_ballotpedia_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_candidate_analysis_done',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_facebook_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_linkedin_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_twitter_handle_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_wikipedia_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidatechangelog',
            name='is_from_twitter',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
