# Generated by Django 3.2.24 on 2024-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20240214_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='race_office_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='race office level'),
        ),
    ]
