# Generated by Django 3.2.25 on 2024-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_candidatecampaign_race_office_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_ballotpedia_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_candidate_url_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_candidate_url_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_facebook_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_linkedin_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_official_statement_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_official_statement_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_photo_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_photo_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_twitter_handle_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_website_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_website_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_wikipedia_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_withdrawal_date_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_withdrawal_date_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
