# Generated by Django 3.2.25 on 2024-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_auto_20240407_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_link_to_office_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_link_to_office_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
