# Generated by Django 5.0.3 on 2024-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_auto_20240409_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='profile_image_background_color_needed',
            field=models.BooleanField(null=True),
        ),
    ]
