# Generated by Django 5.0.3 on 2024-05-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0026_candidatecampaign_profile_image_background_color_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='ballotpedia_photo_url_is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
