# Generated by Django 5.0.3 on 2024-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_candidatecampaign_ballotpedia_photo_url_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='facebook_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='facebook_photo_url_is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
