# Generated by Django 5.0.3 on 2024-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0029_candidatecampaign_facebook_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='facebook_photo_url_is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
