# Generated by Django 5.0.3 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0030_candidatecampaign_facebook_photo_url_is_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='wikipedia_photo_does_not_exist',
            field=models.BooleanField(default=False),
        ),
    ]
