# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0031_candidatecampaign_wikipedia_photo_does_not_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_contact_form_url',
            field=models.TextField(null=True, verbose_name='website url of candidate contact form'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_url',
            field=models.TextField(null=True, verbose_name='website url of candidate'),
        ),
    ]
