# Generated by Django 5.0.3 on 2024-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_alter_candidatecampaign_candidate_contact_form_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='ballotpedia_candidate_links_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
