# Generated by Django 5.0.3 on 2024-06-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_candidatecampaign_ballotpedia_candidate_links_retrieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatesArePossibleDuplicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate1_we_vote_id', models.CharField(max_length=255, null=True)),
                ('candidate2_we_vote_id', models.CharField(max_length=255, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
