# Generated by Django 5.0.3 on 2024-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0034_candidatesarepossibleduplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='politician_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='politician unique identifier'),
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='politician_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='we vote politician id'),
        ),
    ]
