# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0035_alter_candidatecampaign_politician_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='ctcl_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='ctcl uuid'),
        ),
    ]
