# Generated by Django 5.0.3 on 2024-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_alter_candidatecampaign_ctcl_uuid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['seo_friendly_path', 'politician_we_vote_id'], name='candidate_c_seo_fri_694764_idx'),
        ),
    ]
