# Generated by Django 5.0.3 on 2024-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0037_candidatecampaign_candidate_c_seo_fri_694764_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidatecampaign',
            name='candidate_c_seo_fri_694764_idx',
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['seo_friendly_path', 'politician_we_vote_id', '-id'], name='candidate_seo_friendly_path1'),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['politician_we_vote_id', 'seo_friendly_path', '-id'], name='candidate_seo_friendly_path2'),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['politician_we_vote_id', 'candidate_name', 'candidate_twitter_handle', 'candidate_twitter_handle2', 'candidate_twitter_handle3'], name='candidate_list_for_politician'),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['politician_we_vote_id', 'linked_campaignx_we_vote_id', '-id'], name='politician_linked_campaignx'),
        ),
    ]
