# Generated by Django 5.0.3 on 2024-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0038_remove_candidatecampaign_candidate_c_seo_fri_694764_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['politician_we_vote_id', 'candidate_name'], name='list_politician_and_name'),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['candidate_twitter_handle', 'candidate_twitter_handle2', 'candidate_twitter_handle3'], name='candidate_list_twitter'),
        ),
    ]
