# Generated by Django 5.0.3 on 2024-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0039_candidatecampaign_list_politician_and_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidatecampaign',
            name='candidate_list_for_politician',
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['candidate_name', 'politician_we_vote_id', 'candidate_twitter_handle', 'candidate_twitter_handle2', 'candidate_twitter_handle3'], name='candidate_list_for_politician'),
        ),
    ]
