# Generated by Django 5.0.8 on 2024-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_remove_candidatecampaign_candidate_list_for_politician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecampaign',
            name='candidate_year',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['candidate_year'], name='candidate_year_index'),
        ),
        migrations.AddIndex(
            model_name='candidatecampaign',
            index=models.Index(fields=['we_vote_id', 'candidate_year'], name='candidate_id_year'),
        ),
    ]
