# Generated by Django 5.0.8 on 2024-10-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0041_alter_candidatecampaign_candidate_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCTCLAlternateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctcl_uuid_primary', models.CharField(max_length=36, null=True)),
                ('ctcl_uuid_alternate', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatecampaign',
            name='crowdpac_candidate_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
