# Generated by Django 5.0.13 on 2025-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0042_candidatectclalternatemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='bluesky_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='tiktok_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_bluesky_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_bluesky_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_tiktok_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_tiktok_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
