# Generated by Django 5.0.13 on 2025-10-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0043_candidatecampaign_bluesky_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='is_claimed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
