# Generated by Django 5.0.13 on 2025-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0044_candidatecampaign_is_claimed_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='candidate_ultimate_election_date_calculated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='contest_office_name_calculated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
