# Generated by Django 5.0.13 on 2025-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_candidatecampaign_candidate_ultimate_election_date_calculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='threads_handle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_threads_handle_added',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='candidatechangelog',
            name='is_threads_handle_removed',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
