# Generated by Django 5.0.13 on 2025-11-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0046_candidatecampaign_threads_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduplicationNeededForStateToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now_as_integer', models.PositiveIntegerField(db_index=True, null=True, unique=True)),
                ('ak_deduplication_needed', models.BooleanField(default=True)),
                ('al_deduplication_needed', models.BooleanField(default=True)),
                ('ar_deduplication_needed', models.BooleanField(default=True)),
                ('az_deduplication_needed', models.BooleanField(default=True)),
                ('ca_deduplication_needed', models.BooleanField(default=True)),
                ('co_deduplication_needed', models.BooleanField(default=True)),
                ('ct_deduplication_needed', models.BooleanField(default=True)),
                ('dc_deduplication_needed', models.BooleanField(default=True)),
                ('de_deduplication_needed', models.BooleanField(default=True)),
                ('fl_deduplication_needed', models.BooleanField(default=True)),
                ('ga_deduplication_needed', models.BooleanField(default=True)),
                ('hi_deduplication_needed', models.BooleanField(default=True)),
                ('ia_deduplication_needed', models.BooleanField(default=True)),
                ('id_deduplication_needed', models.BooleanField(default=True)),
                ('il_deduplication_needed', models.BooleanField(default=True)),
                ('in_deduplication_needed', models.BooleanField(default=True)),
                ('ks_deduplication_needed', models.BooleanField(default=True)),
                ('ky_deduplication_needed', models.BooleanField(default=True)),
                ('la_deduplication_needed', models.BooleanField(default=True)),
                ('ma_deduplication_needed', models.BooleanField(default=True)),
                ('md_deduplication_needed', models.BooleanField(default=True)),
                ('me_deduplication_needed', models.BooleanField(default=True)),
                ('mi_deduplication_needed', models.BooleanField(default=True)),
                ('mn_deduplication_needed', models.BooleanField(default=True)),
                ('mo_deduplication_needed', models.BooleanField(default=True)),
                ('ms_deduplication_needed', models.BooleanField(default=True)),
                ('mt_deduplication_needed', models.BooleanField(default=True)),
                ('na_deduplication_needed', models.BooleanField(default=True)),
                ('nc_deduplication_needed', models.BooleanField(default=True)),
                ('nd_deduplication_needed', models.BooleanField(default=True)),
                ('ne_deduplication_needed', models.BooleanField(default=True)),
                ('nh_deduplication_needed', models.BooleanField(default=True)),
                ('nj_deduplication_needed', models.BooleanField(default=True)),
                ('nm_deduplication_needed', models.BooleanField(default=True)),
                ('nv_deduplication_needed', models.BooleanField(default=True)),
                ('ny_deduplication_needed', models.BooleanField(default=True)),
                ('oh_deduplication_needed', models.BooleanField(default=True)),
                ('ok_deduplication_needed', models.BooleanField(default=True)),
                ('or_deduplication_needed', models.BooleanField(default=True)),
                ('pa_deduplication_needed', models.BooleanField(default=True)),
                ('pr_deduplication_needed', models.BooleanField(default=True)),
                ('ri_deduplication_needed', models.BooleanField(default=True)),
                ('sc_deduplication_needed', models.BooleanField(default=True)),
                ('sd_deduplication_needed', models.BooleanField(default=True)),
                ('tn_deduplication_needed', models.BooleanField(default=True)),
                ('tx_deduplication_needed', models.BooleanField(default=True)),
                ('ut_deduplication_needed', models.BooleanField(default=True)),
                ('va_deduplication_needed', models.BooleanField(default=True)),
                ('vt_deduplication_needed', models.BooleanField(default=True)),
                ('wa_deduplication_needed', models.BooleanField(default=True)),
                ('wi_deduplication_needed', models.BooleanField(default=True)),
                ('wv_deduplication_needed', models.BooleanField(default=True)),
                ('wy_deduplication_needed', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='duplicate_check_last_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='updated_from_politician_completed_first',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='updated_from_politician_completed_second',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='candidatecampaign',
            name='updates_to_politician_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
