# Generated by Django 5.0.13 on 2026-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0047_deduplicationneededforstatetoday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecampaign',
            name='opposers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
