# Generated by Django 5.0.13 on 2026-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraApiCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_action', models.DateTimeField(auto_now=True, verbose_name='date and time of action')),
                ('kind_of_action', models.CharField(blank=True, max_length=50, null=True, verbose_name='kind of call to jira')),
            ],
            options={
                'verbose_name': 'JIRA API Counter',
                'verbose_name_plural': 'JIRA API Counters',
                'db_table': 'jira_api_counter',
            },
        ),
    ]
