# Generated by Django 3.2.13 on 2022-07-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0002_alter_emailoutbounddescription_kind_of_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbounddescription',
            name='list_unsubscribe_mailto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailoutbounddescription',
            name='list_unsubscribe_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='list_unsubscribe_mailto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='list_unsubscribe_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
