# Generated by Django 3.2.15 on 2022-10-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0003_auto_20220720_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbounddescription',
            name='kind_of_email_template',
            field=models.CharField(choices=[('GENERIC_EMAIL_TEMPLATE', 'Generic Email'), ('FRIEND_ACCEPTED_INVITATION_TEMPLATE', 'Accept an invitation to be a Friend'), ('FRIEND_INVITATION_TEMPLATE', 'Invite Friend'), ('LINK_TO_SIGN_IN_TEMPLATE', 'Link to sign in.'), ('MESSAGE_TO_FRIEND_TEMPLATE', 'Message to friend'), ('NOTICE_FRIEND_ENDORSEMENTS_TEMPLATE', 'New opinion from Friend.'), ('NOTICE_VOTER_DAILY_SUMMARY_TEMPLATE', 'Daily summary of activity for the voter.'), ('REMIND_CONTACT', 'Remind contact to vote'), ('VERIFY_EMAIL_ADDRESS_TEMPLATE', 'Verify Senders Email Address'), ('SEND_BALLOT_TO_SELF', 'Send ballot to self'), ('SEND_BALLOT_TO_FRIENDS', 'Send ballot to friends'), ('SIGN_IN_CODE_EMAIL_TEMPLATE', 'Send code to verify sign in.')], default='GENERIC_EMAIL_TEMPLATE', max_length=50),
        ),
    ]
