# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0004_alter_emailoutbounddescription_kind_of_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the email owner'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote id of this email address'),
        ),
        migrations.AlterField(
            model_name='emailoutbounddescription',
            name='recipient_email_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='email we vote id for recipient'),
        ),
        migrations.AlterField(
            model_name='emailoutbounddescription',
            name='recipient_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the recipient if we have it'),
        ),
        migrations.AlterField(
            model_name='emailoutbounddescription',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
        migrations.AlterField(
            model_name='emailscheduled',
            name='recipient_email_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the email'),
        ),
        migrations.AlterField(
            model_name='emailscheduled',
            name='recipient_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the recipient'),
        ),
        migrations.AlterField(
            model_name='emailscheduled',
            name='sender_voter_we_vote_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='we vote id for the sender'),
        ),
    ]
