# Generated by Django 5.0.13 on 2025-10-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0005_alter_emailaddress_voter_we_vote_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_campaign_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('email_body_template_raw', models.TextField(blank=True, null=True)),
                ('email_subject_template_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('email_template_id', models.PositiveIntegerField(default=0)),
                ('emails_sent', models.BooleanField(default=False)),
                ('is_for_politician', models.BooleanField(default=False)),
                ('is_for_staff', models.BooleanField(default=False)),
                ('is_for_voter', models.BooleanField(default=False)),
                ('voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignLabelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_campaign_id', models.PositiveIntegerField(default=0)),
                ('email_campaign_label_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_body_assembled', models.TextField(blank=True, null=True)),
                ('email_campaign_id', models.PositiveIntegerField(default=0)),
                ('email_scheduled', models.BooleanField(default=False)),
                ('email_subject_assembled', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('email_template_folder_id', models.PositiveIntegerField(default=0)),
                ('email_template_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='emailoutbounddescription',
            name='kind_of_email_template',
            field=models.CharField(choices=[('GENERIC_EMAIL_TEMPLATE', 'Generic Email'), ('FROM_TEMPLATE_SYSTEM', 'From Dynamic Email Template'), ('FRIEND_ACCEPTED_INVITATION_TEMPLATE', 'Accept an invitation to be a Friend'), ('FRIEND_INVITATION_TEMPLATE', 'Invite Friend'), ('LINK_TO_SIGN_IN_TEMPLATE', 'Link to sign in.'), ('MESSAGE_TO_FRIEND_TEMPLATE', 'Message to friend'), ('NOTICE_FRIEND_ENDORSEMENTS_TEMPLATE', 'New opinion from Friend.'), ('NOTICE_VOTER_DAILY_SUMMARY_TEMPLATE', 'Daily summary of activity for the voter.'), ('REMIND_CONTACT', 'Remind contact to vote'), ('VERIFY_EMAIL_ADDRESS_TEMPLATE', 'Verify Senders Email Address'), ('SEND_BALLOT_TO_SELF', 'Send ballot to self'), ('SEND_BALLOT_TO_FRIENDS', 'Send ballot to friends'), ('SIGN_IN_CODE_EMAIL_TEMPLATE', 'Send code to verify sign in.')], default='GENERIC_EMAIL_TEMPLATE', max_length=50),
        ),
    ]
