# Generated by Django 5.0.13 on 2025-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0006_emailcampaign_emailcampaignlabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_folder_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
