# Generated by Django 5.0.13 on 2025-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0007_alter_emailtemplate_email_template_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipientTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('has_email', models.BooleanField(default=None, null=True)),
                ('has_no_email', models.BooleanField(default=None, null=True)),
                ('has_no_sms', models.BooleanField(default=None, null=True)),
                ('has_sms', models.BooleanField(default=None, null=True)),
                ('include_candidates_from_prior_elections', models.BooleanField(default=None, null=True)),
                ('is_candidate', models.BooleanField(default=None, null=True)),
                ('is_organization', models.BooleanField(default=None, null=True)),
                ('is_politician', models.BooleanField(default=None, null=True)),
                ('is_voter', models.BooleanField(default=None, null=True)),
                ('parent_template_operator', models.CharField(db_index=True, max_length=16, null=True)),
                ('parent_recipient_template_id', models.PositiveIntegerField(default=0, null=True)),
                ('recipient_template_folder_id', models.PositiveIntegerField(default=0, null=True)),
                ('recipient_template_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('search_google_civic_election_id', models.PositiveIntegerField(default=0, null=True)),
                ('search_term_candidate', models.CharField(max_length=255, null=True)),
                ('search_term_organization', models.CharField(max_length=255, null=True)),
                ('search_term_politician', models.CharField(max_length=255, null=True)),
                ('search_term_political_party', models.CharField(max_length=255, null=True)),
                ('search_term_state_code', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipientTemplateFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_template_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipientTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_campaign_id', models.PositiveIntegerField(default=0, null=True)),
                ('recipient_template_id', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='candidate_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='organization_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
    ]
