# Generated by Django 5.0.13 on 2025-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0008_emailrecipienttemplate_emailrecipienttemplatefolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='email_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
