# Generated by Django 5.0.13 on 2026-01-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0009_emailcampaign_scheduled_send_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='from_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='from_email_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='reply_to_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
