# Generated by Django 5.0.13 on 2026-01-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0010_emailcampaign_from_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaignrecipient',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_by_voter_we_vote_id',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='list_unsubscribe_mailto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='list_unsubscribe_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='political_party',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_passkey',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_seo_friendly_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_state_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_email_subscription_secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_email_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='recipient_voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_email_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='sender_voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='supporters_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='email_campaign_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailscheduled',
            name='email_campaign_recipient_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailscheduled',
            name='email_outbound_description_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
