# Generated by Django 5.0.13 on 2026-02-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0012_emailaudiencebuilder_emailaudiencebuilderfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='open_tracking_code',
            field=models.CharField(db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='open_tracking_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='open_tracking_first_open',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='open_tracking_last_open',
            field=models.DateTimeField(null=True),
        ),
    ]
