# Generated by Django 5.0.13 on 2026-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0014_audiencebuilder_audiencefilter_audiencefilterchain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter1_to_filter2_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter2_to_filter3_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter3_to_filter4_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter4_to_filter5_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter5_to_filter6_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter6_to_filter7_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter7_to_filter8_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilterchain',
            name='filter8_to_filter9_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('EXCLUDE', 'EXCLUDE'), ('INCLUDE', 'INCLUDE'), ('OR', 'OR')], default=None, max_length=24, null=True),
        ),
    ]
