# Generated by Django 5.0.13 on 2026-02-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0015_alter_audiencefilterchain_filter1_to_filter2_operator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_contact_contains',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_contact_exists',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_contact_is_missing',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_date_is_after',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_date_is_before',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_date_is_on',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_date_is_on_or_after',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_date_is_on_or_before',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_is',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_is_not',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_at_least_once',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_last_24_hours',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_last_3_days',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_last_month',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_last_week',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_last_year',
        ),
        migrations.RemoveField(
            model_name='audiencefilter',
            name='boolean_relative_never',
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='audience_type_modifier',
            field=models.CharField(choices=[('AUDIENCE_TYPE_IS', 'is'), ('AUDIENCE_TYPE_IS_NOT', 'is not')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='election_modifier',
            field=models.CharField(choices=[('ELECTION_IS_AFTER', 'is after'), ('ELECTION_IS_BEFORE', 'is before'), ('ELECTION_IS_ON', 'is on'), ('ELECTION_IS_ON_OR_AFTER', 'is on or after'), ('ELECTION_IS_ON_OR_BEFORE', 'is on or before')], default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='email_address_contains_list',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='email_address_modifier',
            field=models.CharField(choices=[('EMAIL_ADDRESS_CONTAINS', 'contains'), ('EMAIL_ADDRESS_EXISTS', 'exists'), ('EMAIL_ADDRESS_IS_MISSING', 'is missing')], default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='email_campaign_id_list',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='has_been_contacted_modifier',
            field=models.CharField(choices=[('HAS_BEEN_CONTACTED_AT_LEAST_ONCE', 'at least once'), ('HAS_BEEN_CONTACTED_LAST_DAY', 'in last day'), ('HAS_BEEN_CONTACTED_LAST_3_DAYS', 'in last 3 days'), ('HAS_BEEN_CONTACTED_LAST_WEEK', 'in last week'), ('HAS_BEEN_CONTACTED_LAST_MONTH', 'in last month'), ('HAS_BEEN_CONTACTED_LAST_YEAR', 'in last year'), ('HAS_BEEN_CONTACTED_NEVER', 'never')], default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='has_claimed_politician_modifier',
            field=models.CharField(choices=[('HAS_CLAIMED_POLITICIAN_AT_LEAST_ONCE', 'at least once'), ('HAS_CLAIMED_POLITICIAN_LAST_DAY', 'in last day'), ('HAS_CLAIMED_POLITICIAN_LAST_3_DAYS', 'in last 3 days'), ('HAS_CLAIMED_POLITICIAN_LAST_WEEK', 'in last week'), ('HAS_CLAIMED_POLITICIAN_LAST_MONTH', 'in last month'), ('HAS_CLAIMED_POLITICIAN_LAST_YEAR', 'in last year'), ('HAS_CLAIMED_POLITICIAN_NEVER', 'never')], default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='has_opened_list',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='has_opened_modifier',
            field=models.CharField(choices=[('HAS_OPENED_ANY', 'any'), ('HAS_OPENED_ALL', 'all'), ('HAS_NOT_OPENED_ANY', 'none'), ('HAS_NOT_OPENED_AT_LEAST_ONE', 'not all (missed at least one)')], default=None, max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='has_signed_in_modifier',
            field=models.CharField(choices=[('HAS_SIGNED_IN_AT_LEAST_ONCE', 'at least once'), ('HAS_SIGNED_IN_LAST_DAY', 'in last day'), ('HAS_SIGNED_IN_LAST_3_DAYS', 'in last 3 days'), ('HAS_SIGNED_IN_LAST_WEEK', 'in last week'), ('HAS_SIGNED_IN_LAST_MONTH', 'in last month'), ('HAS_SIGNED_IN_LAST_YEAR', 'in last year'), ('HAS_SIGNED_IN_NEVER', 'never')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='phone_number_modifier',
            field=models.CharField(choices=[('PHONE_NUMBER_CONTAINS', 'contains area code'), ('PHONE_NUMBER_EXISTS', 'exists'), ('PHONE_NUMBER_IS_MISSING', 'is missing')], default=None, max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='state_modifier',
            field=models.CharField(choices=[('STATE_IS', 'is'), ('STATE_IS_NOT', 'is not')], default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='date_last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='audiencefilter',
            name='audience_filter_type',
            field=models.CharField(choices=[('FILTER_TYPE_AUDIENCE_TYPE', 'Audience type'), ('FILTER_TYPE_ELECTION_DATE', 'Election date'), ('FILTER_TYPE_EMAIL_ADDRESS', 'Email address'), ('FILTER_TYPE_HAS_BEEN_CONTACTED', 'Has been contacted'), ('FILTER_TYPE_HAS_CLAIMED_POLITICIAN', 'Has claimed profile'), ('FILTER_TYPE_HAS_OPENED', 'Has opened'), ('FILTER_TYPE_HAS_SIGNED_IN', 'Has signed in'), ('FILTER_TYPE_PHONE_NUMBER', 'Phone number'), ('FILTER_TYPE_POLITICAL_PARTY', 'Political party'), ('FILTER_TYPE_STATE_CODE', 'State code')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilter',
            name='state_code_list',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
