# Generated by Django 5.0.13 on 2026-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0016_remove_audiencefilter_boolean_contact_contains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='audience_builder_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
