# Generated by Django 5.0.13 on 2026-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0017_emailcampaign_audience_builder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='bounce_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='date_sent',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='recipient_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
