# Generated by Django 5.0.13 on 2026-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0018_emailcampaign_bounce_count_emailcampaign_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencefilter',
            name='was_sent_campaign_list',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='audiencefilter',
            name='was_sent_campaign_modifier',
            field=models.CharField(choices=[('WAS_SENT_CAMPAIGN_ANY', 'any'), ('WAS_SENT_CAMPAIGN_ALL', 'all'), ('WAS_NOT_SENT_CAMPAIGN_ANY', 'none'), ('WAS_NOT_SENT_CAMPAIGN_AT_LEAST_ONE', 'not all (missed at least one)')], default=None, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='audiencefilter',
            name='audience_filter_type',
            field=models.CharField(choices=[('FILTER_TYPE_AUDIENCE_TYPE', 'Audience type'), ('FILTER_TYPE_ELECTION_DATE', 'Election date'), ('FILTER_TYPE_EMAIL_ADDRESS', 'Email address'), ('FILTER_TYPE_HAS_BEEN_CONTACTED', 'Has been contacted'), ('FILTER_TYPE_HAS_CLAIMED_POLITICIAN', 'Has claimed profile'), ('FILTER_TYPE_HAS_OPENED', 'Has opened'), ('FILTER_TYPE_HAS_SIGNED_IN', 'Has signed in'), ('FILTER_TYPE_PHONE_NUMBER', 'Phone number'), ('FILTER_TYPE_POLITICAL_PARTY', 'Political party'), ('FILTER_TYPE_STATE_CODE', 'State code'), ('FILTER_TYPE_WAS_SENT_CAMPAIGN', 'Was sent campaign')], default=None, max_length=50, null=True),
        ),
    ]
