# Generated by Django 5.0.13 on 2026-03-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0019_audiencefilter_was_sent_campaign_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('s3_key', models.CharField(max_length=1024)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_inline', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_outbound.emailcampaign')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_outbound.emailtemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailattachments',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email_template__isnull', False), ('email_campaign__isnull', True), ('draft_uuid__isnull', True)), models.Q(('email_template__isnull', True), ('email_campaign__isnull', False), ('draft_uuid__isnull', True)), models.Q(('email_template__isnull', True), ('email_campaign__isnull', True), ('draft_uuid__isnull', False)), _connector='OR'), name='attachment_exactly_one_owner'),
        ),
    ]
