# Generated by Django 5.0.13 on 2026-04-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0020_emailattachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='include_footer',
            field=models.BooleanField(default=True),
        ),
    ]
