# Generated by Django 5.2.16 on 2026-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_outbound', '0021_emailcampaign_include_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaignrecipient',
            name='politician_email_subscription_secret_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
