# Generated by Django 3.2.13 on 2022-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(null=True, verbose_name='stripe dispute creation timestamp')),
                ('etype', models.CharField(blank=True, max_length=32, null=True, verbose_name='stripe transaction type')),
                ('reason', models.CharField(blank=True, max_length=32, null=True, verbose_name='stripe dispute cause')),
                ('transaction_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='stripe transaction status')),
                ('amount', models.IntegerField(default=0, verbose_name='disputed stripe charge amount')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='stripe dispute description')),
                ('fee', models.IntegerField(default=0, verbose_name='disputed stripe charge fee amount')),
                ('total_cost', models.IntegerField(default=0, verbose_name='net charge by stripe including fees')),
                ('fee_description', models.CharField(blank=True, max_length=32, null=True, verbose_name='stripe dispute fee description')),
                ('evidence_due_by', models.DateTimeField(null=True, verbose_name='stripe deadline for submitting evidence')),
                ('billing_address', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name="stripe returns the fraud initiator's zip code")),
                ('customer_email_address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name="stripe returns fraud initiator's email address as a name")),
                ('customer_name', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name="stripe returns the disputed customer's name")),
                ('customer_purchase_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='Client IP address as seen by Stripe')),
                ('charge_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe charge id')),
                ('dispute_source_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe dispute id')),
                ('balance_transaction_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe transaction id')),
                ('transaction_state', models.CharField(blank=True, max_length=32, null=True, verbose_name='Stripe transaction state')),
                ('evidence_has_evidence', models.BooleanField(default=False, verbose_name='We vote has submitted evidence about the transaction')),
                ('evidence_past_due', models.BooleanField(default=False, verbose_name='We vote did not submit evidence in time')),
                ('evidence_submission_count', models.IntegerField(default=0, verbose_name='Number of times evidence has been submitted')),
                ('livemode', models.BooleanField(default=False, verbose_name='True: Live transaction, False: Test transaction')),
            ],
        ),
    ]
