# Generated by Django 5.0.8 on 2024-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_we_vote_id', models.CharField(db_index=True, max_length=255)),
                ('date_last_changed', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('is_subscribed_by_email', models.BooleanField(default=None, null=True)),
                ('linked_position_we_vote_id', models.CharField(max_length=255, null=True)),
                ('organization_we_vote_id', models.CharField(max_length=255, null=True)),
                ('participant_name', models.CharField(max_length=255, null=True)),
                ('participant_endorsement', models.TextField(null=True)),
                ('visibility_blocked_by_we_vote', models.BooleanField(default=False)),
                ('visible_to_public', models.BooleanField(default=True)),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChallengeSupporter',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='supporters_count',
            new_name='participants_count',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='supporters_count_minimum_ignored',
            new_name='participants_count_minimum_ignored',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='supporters_count_to_update_with_bulk_script',
            new_name='participants_count_to_update_with_bulk_script',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='supporters_count_victory_goal',
            new_name='participants_count_victory_goal',
        ),
    ]
