# Generated by Django 5.0.8 on 2024-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challengeparticipant_delete_challengesupporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='is_subscribed_by_email',
        ),
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='linked_position_we_vote_id',
        ),
        migrations.RemoveField(
            model_name='challengeparticipant',
            name='participant_endorsement',
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='custom_message_for_friends',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='friends_invited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='friends_who_joined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='friends_who_viewed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='friends_who_viewed_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
