# Generated by Django 5.0.8 on 2024-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_remove_challengeparticipant_is_subscribed_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_joined', models.BooleanField(default=False)),
                ('challenge_we_vote_id', models.CharField(max_length=255)),
                ('custom_message_from_inviter', models.TextField(null=True)),
                ('date_accepted_invite', models.DateTimeField(null=True)),
                ('date_invited', models.DateTimeField(auto_now_add=True, null=True)),
                ('invitee_name', models.CharField(max_length=255, null=True)),
                ('invitee_url_code', models.CharField(max_length=50, null=True)),
                ('inviter_name', models.CharField(max_length=255, null=True)),
                ('inviter_voter_we_vote_id', models.CharField(max_length=255, null=True)),
                ('invite_sent', models.BooleanField(default=False)),
                ('invite_viewed', models.BooleanField(default=False)),
                ('invite_viewed_count', models.PositiveIntegerField(default=0)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='date_challenge_started',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_ends_date_as_integer',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_starts_date_as_integer',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='challenge_we_vote_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='date_last_changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge_we_vote_id', '-points'], name='challenge_points'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['voter_we_vote_id', 'challenge_we_vote_id'], name='voter_challenge_participant'),
        ),
        migrations.AddIndex(
            model_name='challengeinvitee',
            index=models.Index(fields=['invitee_url_code'], name='invitee_url_code_index'),
        ),
        migrations.AddIndex(
            model_name='challengeinvitee',
            index=models.Index(fields=['inviter_voter_we_vote_id', 'challenge_we_vote_id'], name='inviter_challenge_list'),
        ),
    ]
