# Generated by Django 5.0.8 on 2024-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challengeinvitee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeinvitee',
            old_name='custom_message_from_inviter',
            new_name='invite_text_from_inviter',
        ),
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='custom_message_for_friends',
            new_name='invite_text_for_friends',
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_invite_text_default',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='challengeparticipant',
            index=models.Index(fields=['challenge_we_vote_id'], name='challenge_we_vote_id'),
        ),
    ]
