# Generated by Django 5.0.8 on 2024-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_rename_custom_message_from_inviter_challengeinvitee_invite_text_from_inviter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeinvitee',
            old_name='date_accepted_invite',
            new_name='date_challenge_joined',
        ),
        migrations.RenameField(
            model_name='challengeinvitee',
            old_name='date_invited',
            new_name='date_invite_sent',
        ),
        migrations.AddField(
            model_name='challengeinvitee',
            name='date_invite_viewed',
            field=models.DateTimeField(null=True),
        ),
    ]
