# Generated by Django 5.0.8 on 2024-10-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_rename_date_accepted_invite_challengeinvitee_date_challenge_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='friends_invited',
            new_name='invitees_count',
        ),
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='friends_who_joined',
            new_name='invitees_who_joined',
        ),
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='friends_who_viewed',
            new_name='invitees_who_viewed',
        ),
        migrations.RenameField(
            model_name='challengeparticipant',
            old_name='friends_who_viewed_plus',
            new_name='invitees_who_viewed_plus',
        ),
        migrations.AddField(
            model_name='challenge',
            name='invitees_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
