# Generated by Django 5.0.8 on 2024-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_rename_friends_invited_challengeparticipant_invitees_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeparticipant',
            name='invites_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
