# Generated by Django 5.0.9 on 2024-10-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_challengeparticipant_invites_sent_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeinvitee',
            name='invitee_voter_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challengeinvitee',
            name='invitee_voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challengeinvitee',
            name='parent_invitee_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='inviter_voter_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
