# Generated by Django 5.0.9 on 2024-10-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_challengeinvitee_invitee_voter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='opposers_count',
        ),
    ]
