# Generated by Django 3.2.18 on 2023-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionentered',
            name='position_ultimate_election_not_linked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='positionforfriends',
            name='position_ultimate_election_not_linked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
