# Generated by Django 3.2.18 on 2023-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20230331_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionentered',
            name='campaignx_supporter_created',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='positionforfriends',
            name='campaignx_supporter_created',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
