# Generated by Django 3.2.23 on 2024-01-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20230521_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionentered',
            name='ballot_item_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for candidate, measure, or office'),
        ),
        migrations.AlterField(
            model_name='positionentered',
            name='speaker_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for org or person with position'),
        ),
        migrations.AlterField(
            model_name='positionforfriends',
            name='ballot_item_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for candidate, measure, or office'),
        ),
        migrations.AlterField(
            model_name='positionforfriends',
            name='speaker_twitter_handle',
            field=models.CharField(max_length=255, null=True, verbose_name='twitter username for org or person with position'),
        ),
    ]
