# Generated by Django 5.0.3 on 2024-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_auto_20240129_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionentered',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more info about this position'),
        ),
        migrations.AlterField(
            model_name='positionforfriends',
            name='more_info_url',
            field=models.TextField(null=True, verbose_name='url with more info about this position'),
        ),
    ]
