# Generated by Django 5.0.3 on 2024-07-13 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_alter_positionentered_more_info_url_and_more'),
        ('twitter', '0007_alter_tweet_organization_we_vote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'voter_we_vote_id', 'stance', '-date_entered'], name='positions_for_candidate_index'),
        ),
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'organization_we_vote_id', 'google_civic_election_id', 'stance'], name='positions_for_election_index'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'voter_we_vote_id', 'stance', '-date_entered'], name='friends_positions_candidate'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'organization_we_vote_id', 'google_civic_election_id', 'stance'], name='friends_positions_election'),
        ),
    ]
