# Generated by Django 5.0.3 on 2024-07-13 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_rename_positions_for_candidate_index_positions_for_candidate_voter_and_more'),
        ('twitter', '0007_alter_tweet_organization_we_vote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='positionentered',
            name='positions_for_election_index',
        ),
        migrations.RemoveIndex(
            model_name='positionforfriends',
            name='friends_positions_election',
        ),
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'google_civic_election_id', 'organization_we_vote_id'], name='positions_for_election_index'),
        ),
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['organization_we_vote_id', 'candidate_campaign_we_vote_id'], name='positions_for_org_candidate'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'google_civic_election_id', 'organization_we_vote_id'], name='friends_positions_election'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['organization_we_vote_id', 'candidate_campaign_we_vote_id'], name='friends_for_org_candidate'),
        ),
    ]
