# Generated by Django 5.0.3 on 2024-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_remove_positionentered_positions_for_election_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionentered',
            name='politician_follow_created',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
