# Generated by Django 5.0.3 on 2024-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0009_positionentered_politician_follow_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionentered',
            old_name='politician_follow_created',
            new_name='follow_organization_created',
        ),
        migrations.AddField(
            model_name='positionentered',
            name='follow_organization_analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positionforfriends',
            name='follow_organization_analysis_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positionforfriends',
            name='follow_organization_created',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
