# Generated by Django 5.0.3 on 2024-07-25 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0010_rename_politician_follow_created_positionentered_follow_organization_created_and_more'),
        ('twitter', '0007_alter_tweet_organization_we_vote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionentered',
            name='candidate_campaign_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id for the candidate'),
        ),
        migrations.AlterField(
            model_name='positionforfriends',
            name='candidate_campaign_we_vote_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='we vote permanent id for the candidate'),
        ),
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id'], name='candidate_we_vote_id'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['candidate_campaign_we_vote_id'], name='friends_candidate_we_vote_id'),
        ),
    ]
