# Generated by Django 5.0.3 on 2024-07-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0011_alter_positionentered_candidate_campaign_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionentered',
            name='politician_we_vote_id_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='positionforfriends',
            name='politician_we_vote_id_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
