# Generated by Django 5.0.8 on 2024-09-02 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0012_positionentered_politician_we_vote_id_analyzed_and_more'),
        ('twitter', '0007_alter_tweet_organization_we_vote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='positionentered',
            name='positions_for_org_candidate',
        ),
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'google_civic_election_id'], name='cand_and_election_index'),
        ),
    ]
