# Generated by Django 5.0.8 on 2024-09-04 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0013_remove_positionentered_positions_for_org_candidate_and_more'),
        ('twitter', '0007_alter_tweet_organization_we_vote_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='positionentered',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'voter_we_vote_id', '-date_entered'], name='candidate_voter_date_entered'),
        ),
        migrations.AddIndex(
            model_name='positionforfriends',
            index=models.Index(fields=['candidate_campaign_we_vote_id', 'voter_we_vote_id', '-date_entered'], name='friends_candidate_voter_date'),
        ),
    ]
