# Generated by Django 3.2.13 on 2022-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoterequesthistory',
            name='status',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Request status message'),
        ),
    ]
