# Generated by Django 3.2.16 on 2023-01-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_settings', '0002_alter_remoterequesthistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wevotesetting',
            name='admin_app',
            field=models.BooleanField(default=False, verbose_name='allow changes via admin app'),
        ),
    ]
