# Generated by Django 3.2.17 on 2023-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_settings', '0003_wevotesetting_admin_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterequesthistory',
            name='representative_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remoterequesthistory',
            name='candidate_campaign_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='remoterequesthistory',
            name='organization_we_vote_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
