# Generated by Django 5.0.3 on 2024-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wevote_settings', '0006_alter_remoterequesthistory_kind_of_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoterequesthistory',
            name='kind_of_action',
            field=models.CharField(choices=[('RETRIEVE_UPDATE_DATA_FROM_TWITTER', 'Retrieve updated data from Twitter'), ('RETRIEVE_POSSIBLE_BALLOTPEDIA_PHOTOS', 'Retrieve possible Ballotpedia photos'), ('RETRIEVE_POSSIBLE_FACEBOOK_PHOTOS', 'Retrieve possible Facebook photos'), ('RETRIEVE_POSSIBLE_GOOGLE_LINKS', 'Retrieve possible google links'), ('RETRIEVE_POSSIBLE_TWITTER_HANDLES', 'Retrieve possible twitter handles'), ('RETRIEVE_POSSIBLE_WIKIPEDIA_PHOTOS', 'Retrieve possible Wikipedia photos'), ('STOP_BULK_SEARCH_TWITTER_LINK_POSSIBILITY', 'Stop search for Bulk twitter links'), ('RETRIEVE_POSSIBLE_BALLOTPEDIA_CANDIDATES_LINKS', 'Retrieve possible Ballotpedia candidate links')], max_length=50, null=True, verbose_name='kind of action to take'),
        ),
    ]
