# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotitem',
            name='measure_url',
            field=models.TextField(null=True, verbose_name='url of measure'),
        ),
    ]
