# Generated by Django 5.0.3 on 2024-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_alter_ballotitem_measure_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotreturned',
            name='polling_location_we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='we vote permanent id of the map point'),
        ),
        migrations.AlterField(
            model_name='ballotreturned',
            name='we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id'),
        ),
        migrations.AlterField(
            model_name='ballotreturnedempty',
            name='polling_location_we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='we vote permanent id of the map point'),
        ),
        migrations.AlterField(
            model_name='voterballotsaved',
            name='ballot_returned_we_vote_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, verbose_name='ballot_returned we_vote_id this was copied from'),
        ),
    ]
