# Generated by Django 5.0.3 on 2024-07-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_alter_ballotreturned_polling_location_we_vote_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['google_civic_election_id', 'polling_location_we_vote_id', 'contest_office_we_vote_id'], name='ballot_ball_google__7fb0d0_idx'),
        ),
    ]
