# Generated by Django 5.0.3 on 2024-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0004_ballotitem_ballot_ball_google__7fb0d0_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ballotitem',
            new_name='election_poll_office_index',
            old_name='ballot_ball_google__7fb0d0_idx',
        ),
        migrations.AlterField(
            model_name='ballotreturned',
            name='ballot_location_shortcut',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='the url string to find this location'),
        ),
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['polling_location_we_vote_id', 'contest_office_we_vote_id', 'google_civic_election_id'], name='poll_office_election_index'),
        ),
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['google_civic_election_id', 'polling_location_we_vote_id', 'contest_measure_we_vote_id'], name='election_poll_measure_index'),
        ),
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['polling_location_we_vote_id', 'contest_measure_we_vote_id', 'google_civic_election_id'], name='poll_measure_election_index'),
        ),
    ]
