# Generated by Django 5.0.3 on 2024-07-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0005_rename_ballot_ball_google__7fb0d0_idx_election_poll_office_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotreturned',
            name='we_vote_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='we vote permanent id'),
        ),
        migrations.AddIndex(
            model_name='ballotreturned',
            index=models.Index(fields=['polling_location_we_vote_id', 'text_for_map_search'], name='polling_location_and_text'),
        ),
        migrations.AddIndex(
            model_name='ballotreturned',
            index=models.Index(fields=['polling_location_we_vote_id', 'text_for_map_search', 'id'], name='polling_location_and_text_id'),
        ),
        migrations.AddIndex(
            model_name='ballotreturned',
            index=models.Index(fields=['text_for_map_search', 'polling_location_we_vote_id'], name='text_and_polling_location'),
        ),
        migrations.AddIndex(
            model_name='ballotreturned',
            index=models.Index(fields=['text_for_map_search', 'polling_location_we_vote_id', 'id'], name='text_and_polling_location_id'),
        ),
        migrations.AddIndex(
            model_name='ballotreturned',
            index=models.Index(fields=['we_vote_id'], name='ballot_returned_we_vote_id'),
        ),
    ]
