# Generated by Django 5.0.8 on 2024-09-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0006_alter_ballotreturned_we_vote_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ballotitem',
            name='election_poll_office_index',
        ),
        migrations.RemoveIndex(
            model_name='ballotitem',
            name='poll_office_election_index',
        ),
        migrations.RemoveIndex(
            model_name='ballotitem',
            name='election_poll_measure_index',
        ),
        migrations.RemoveIndex(
            model_name='ballotitem',
            name='poll_measure_election_index',
        ),
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['contest_office_we_vote_id', 'polling_location_we_vote_id', 'google_civic_election_id'], name='office_poll_election_index'),
        ),
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['contest_measure_we_vote_id', 'polling_location_we_vote_id', 'google_civic_election_id'], name='measure_poll_election_index'),
        ),
    ]
