# Generated by Django 5.0.8 on 2024-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0007_remove_ballotitem_election_poll_office_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ballotitem',
            index=models.Index(fields=['google_civic_election_id', 'state_code'], name='election_state_index'),
        ),
    ]
