# Generated by Django 3.2.15 on 2022-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_we_vote_hosted_profile_image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_we_vote_hosted_profile_image_url_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_we_vote_hosted_profile_image_url_tiny',
            field=models.TextField(blank=True, null=True),
        ),
    ]
