# Generated by Django 3.2.15 on 2022-10-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20220810_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='email_secret_key',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='is_remind_contact_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='other_voter_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='other_voter_email_address_text',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='other_voter_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='other_voter_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='other_voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='sms_secret_key',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
