# Generated by Django 3.2.15 on 2022-10-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20221024_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='shared_item_code_ready',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_item_code_remind_contacts',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
