# Generated by Django 3.2.16 on 2022-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20221026_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count_all_opinions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count_no_opinions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count_ready',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_count_remind_contacts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_unique_viewer_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_unique_viewer_count_all_opinions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_unique_viewer_count_no_opinions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_unique_viewer_count_ready',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_link_clicked_unique_viewer_count_remind_contacts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
