# Generated by Django 3.2.16 on 2022-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20221119_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterWhoSharesSummaryAllTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('shared_by_display_name', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_large', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(blank=True, null=True)),
                ('shared_link_clicked_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shared_link_clicked_count_last_updated', models.DateTimeField(null=True)),
                ('shared_link_clicked_unique_viewer_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoterWhoSharesSummaryOneYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_we_vote_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('shared_by_display_name', models.TextField(blank=True, null=True)),
                ('year_as_integer', models.PositiveIntegerField(db_index=True, null=True)),
                ('we_vote_hosted_profile_image_url_large', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_medium', models.TextField(blank=True, null=True)),
                ('we_vote_hosted_profile_image_url_tiny', models.TextField(blank=True, null=True)),
                ('shared_link_clicked_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shared_link_clicked_count_last_updated', models.DateTimeField(null=True)),
                ('shared_link_clicked_unique_viewer_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
