# Generated by Django 3.2.16 on 2022-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_voterwhosharessummaryalltime_voterwhosharessummaryoneyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterwhosharessummaryoneyear',
            name='voter_we_vote_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
