# Generated by Django 3.2.16 on 2022-11-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0007_alter_voterwhosharessummaryoneyear_voter_we_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterwhosharessummaryalltime',
            name='shared_item_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='voterwhosharessummaryoneyear',
            name='shared_item_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
