# Generated by Django 3.2.16 on 2022-11-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_auto_20221122_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_by_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
