# Generated by Django 5.0.3 on 2024-06-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20221128_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='destination_full_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sharedlinkclicked',
            name='destination_full_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supershareitem',
            name='destination_full_url',
            field=models.TextField(null=True),
        ),
    ]
