# Generated by Django 5.0.9 on 2024-10-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_alter_shareditem_destination_full_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareditem',
            name='is_challenge_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareditem',
            name='shared_item_code_challenge',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
